### ISSUE TITLE
Installing SFM in a directory URL under a hostname

### ISSUE THREAD

**Issue by xmacex** [gwu-libraries/sfm-ui#1053]
I am trying to install software (thank you) for research purposes at our institution.

I am not successful at installing SFM under Apache so that it can be accessed in a path in the URL, for instance *https://research-server/sfm*. The frontpage loads fine and redirects to *https://research-server/sfm/ui*. All subsequent requests however, drop the *sfm* in the URL, leading to non-existant pages such as *https://researh-server/accounts/login*.

If I manipulate the request URL in the DOM to send it to https://researh-server/sfm/accounts/login instead, it works fine and I land on the expected page.

What is the way to install SFM in a URL directory path? I would assume a setting next to `SFM_HOSTNAME` and `SFM_PORT` in the *.env* file.

Is this #1048?

**Comment by xmacex** [comment]
I found a round-about solution that works for me. I am changing two Apache2 configuration files, one inside the SFM Docker container and the other one one the host machine. In both, I am moving adding a subdirectory to the URL.

First inside the docker machine in the file */etc/apache2/sites-available/sfm.conf*, accessible in my case by `docker exec -it ac7e65665bd0 bash` I am uncommenting the `WSGIScriptAlias` file and setting it to

```
WSGIScriptAlias /sfm /opt/sfm-ui/sfm/sfm/wsgi.py application-group='%{GLOBAL}' process-group='sfm'
```

Second on the host machine I have */etc/apache2/sites-available/sfm.conf* I have the following

```
<Location /sfm/>
        ProxyPass http://localhost:8080/sfm/ connectiontimeout=30 timeout=900
        ProxyPassReverse http://localhost:8080/sfm/
</Location>
```

After reloading both Apaches in the container as well as on the host with `sudo apache2ctl restart`, the host machine serves SFM from *https://research-machine/sfm* 🎉 

This solution involves changing something inside the SFM Docker container so I guess it's not such a sustainable idea. If anyone has better ideas, I'd be interested.

**Comment by lwrubel** [comment]
Hi, thanks for letting us know how you're trying to use SFM and how you've found a workaround, and for all the detail you shared. We haven't set up SFM in this configuration before, so I can see how the hard-coded URL paths are creating this issue you described.  I don't immediately have a better suggestion, but hard-coded paths and environment variables are something we're going to be looking at in some upcoming work. (#1048 is a slightly different issue, it has to do with better documenting how to find your SFM once you've launched it.)

**Comment by xmacex** [comment]
Thank you for your response @lwrubel, and for sharing the future blueprints. 

While I am not experienced with Django and Docker combo, if I somehow come up with a better solution, I'll try to make sure to share it here.

**Comment by xmacex** [comment]
Seems that data gets collected, but on export I see in `docker-compose logs -f` the following

```
twitterstreamexporter_1         | Starting harvester
twitterstreamexporter_1         | 2021-02-08 06:59:22,955: __main__ --> Initing TwitterStreamExporter
twitterstreamexporter_1         | 2021-02-08 06:59:22,956: sfmutils.consumer --> /sfm-data/containers/a5e55dc36b9f/last_message.json does not exist, so not resuming
twitterstreamexporter_1         | 2021-02-08 06:59:22,968: kombu.mixins --> Connected to amqp://sfm_user:**@mq:5672//
twitterstreamexporter_1         | 2021-02-08 07:03:10,307: sfmutils.exporter --> Performing export b3651e64415b4fa58d8bbbc84435b731
twitterstreamexporter_1         | Traceback (most recent call last):
twitterstreamexporter_1         |   File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 623, in _receive_callback
twitterstreamexporter_1         |     return on_m(message) if on_m else self.receive(decoded, message)
twitterstreamexporter_1         |   File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 589, in receive
twitterstreamexporter_1         |     [callback(body, message) for callback in callbacks]
twitterstreamexporter_1         |   File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 589, in <listcomp>
twitterstreamexporter_1         |     [callback(body, message) for callback in callbacks]
twitterstreamexporter_1         |   File "/usr/local/lib/python3.6/site-packages/sfmutils/consumer.py", line 111, in _callback
twitterstreamexporter_1         |     self.on_message()
twitterstreamexporter_1         |   File "/usr/local/lib/python3.6/site-packages/sfmutils/exporter.py", line 80, in on_message
twitterstreamexporter_1         |     harvest_date_start, harvest_date_end)
twitterstreamexporter_1         |   File "/usr/local/lib/python3.6/site-packages/sfmutils/exporter.py", line 202, in _get_warc_paths
twitterstreamexporter_1         |     harvest_date_start=harvest_date_start, harvest_date_end=harvest_date_end):
twitterstreamexporter_1         |   File "/usr/local/lib/python3.6/site-packages/sfmutils/api_client.py", line 28, in _get
twitterstreamexporter_1         |     resp.raise_for_status()
twitterstreamexporter_1         |   File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
twitterstreamexporter_1         |     raise HTTPError(http_error_msg, response=self)
twitterstreamexporter_1         | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://api:8080/api/v1/warcs/?collection=a78ddb9dcb414c8c9c5f014269108639
twitterstreamexporter_1         | 
twitterstreamexporter_1         | The above exception was the direct cause of the following exception:
twitterstreamexporter_1         | 
twitterstreamexporter_1         | Traceback (most recent call last):
twitterstreamexporter_1         |   File "twitter_stream_exporter.py", line 27, in <module>
twitterstreamexporter_1         |     TwitterStreamExporter.main(TwitterStreamExporter, QUEUE, [FILTER_ROUTING_KEY, SAMPLE_ROUTING_KEY])
twitterstreamexporter_1         |   File "/usr/local/lib/python3.6/site-packages/sfmutils/exporter.py", line 286, in main
twitterstreamexporter_1         |     exporter.run()
twitterstreamexporter_1         |   File "/usr/local/lib/python3.6/site-packages/kombu/mixins.py", line 170, in run
twitterstreamexporter_1         |     for _ in self.consume(limit=None, **kwargs):
twitterstreamexporter_1         |   File "/usr/local/lib/python3.6/site-packages/kombu/mixins.py", line 192, in consume
twitterstreamexporter_1         |     conn.drain_events(timeout=safety_interval)
twitterstreamexporter_1         |   File "/usr/local/lib/python3.6/site-packages/librabbitmq/__init__.py", line 227, in drain_events
twitterstreamexporter_1         |     self._basic_recv(timeout)
```

Notice the

    twitterstreamexporter_1         | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://api:8080/api/v1/warcs/?collection=a78ddb9dcb414c8c9c5f014269108639

This seems seems to leave the export hanging and reading the source I fail to understand where to set the `base_api_url` for the application to use it.

If I navigate to *http://research-server:8080/api/v1/warcs/?collection=a78ddb9dcb414c8c9c5f014269108639* I can see the WARC collection. If I investigate the path in it's `results[0].path` at */sfm-data/collection_set/c88a6dc9ce7342b78fe54bbc3deff803/a78ddb9dcb414c8c9c5f014269108639/2021/02/08/11/f890df62efeb44b8a65b1bac32eeea2b-20210208115254967-00000-ugvf50mx.warc.gz*, I see a nice file sitting there on disk.

**Comment by xmacex** [comment]
Changed `/opt/sfm-setup/invoke.sh` line 10 setting for the API base URL

    http://api:8080/

to be

    http://api:8080/sfm/

After some error messages and studying the documentation of [`urlparse.urljoin`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin) plus [this StackOverflow item](https://stackoverflow.com/questions/10893374/python-confusions-with-urljoin), I added the following lines of code to `/usr/local/lib/python3.6/site-packages/sfmutils/api_client.py` on the *twitterstreamexporter* container.

```python
if url_part[0] == '/':
    url_part == url_part[1:]
```

What this does is forces the API url calls to be relative rather than absolute paths, in the case of this particular exporter. Now the export of a Twitter filter query works and I just downloaded a CSV.

Absolutely a botch job and these hacks won't even persist across restarts of the Docker Compose cluster setup – I honestly have no idea how to deal with Docker ¯\\_(ツ)_/¯
