### ISSUE TITLE
Create Sina Weibo harvester

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#109]
Details (which API calls to use etc.) TBD on 30-Dec-2015

**Comment by kerchner** [comment]
Basic harvesting to include:
- Set up friendships outside the app - on the Weibo platform
- Use statuses/friends_timeline (or home_timeline) to get posts 
- Get friendships list using the API (and archive the response)
- Pass current friendships list back with harvest.status message

**Comment by kerchner** [comment]
Keyword search will have to wait for later.  Requires advanced level API access.  We can consider statuses/public_timeline to bring ywow-like capability into SFM.

**Comment by Tanych** [comment]
The basic weibo harvester solution will post on this [repos](https://github.com/gwu-libraries/sfm-weibo-harvester).

**Comment by Tanych** [comment]
Related to repos [sfm-weibo-harverster](https://github.com/gwu-libraries/sfm-weibo-harvester) and [weibowarc](https://github.com/gwu-libraries/weibowarc)

**Comment by justinlittman** [comment]
Note:  Need to split requirements.txt (see one of the other harvesters).

**Comment by justinlittman** [comment]
In weibowarc, are there functions that can be imported from twarc rather than duplicated?

Also, "twarc" is short for "twitter archiver".  It really has nothing to do with WARCs.  I would suggest "weiboarc" or "weibarc" might be less confusing, but still in the same vein as twarc.

**Comment by Tanych** [comment]
@justinlittman  I think it's possible but there are a little different with twarc.  The response header is also different.  I will fix them.

**Comment by justinlittman** [comment]
A few more notes:
* The README description of test_config.py does not match tests/__init__.py.  tests/__init__.py expects a WEIBO_ prefix.
* When I ran the tests from within the docker container, I got:
```
(ENV)GLSS-F0G5RP:sfm-weibo-harvester justinlittman$ docker exec docker_sfmweiboharvester_1 python -m unittest discover
E
======================================================================
ERROR: tests.test_weibo_harvester (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_weibo_harvester
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/opt/sfm-weibo-harvester/tests/__init__.py", line 14, in <module>
    test_config_available = True if WEIBO_API_KEY and WEIBO_API_SECRET \
NameError: name 'WEIBO_API_KEY' is not defined


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
(ENV)GLSS-F0G5RP:sfm-weibo-harvester justinlittman$ vi test_config.py
(ENV)GLSS-F0G5RP:sfm-weibo-harvester justinlittman$ docker exec docker_sfmweiboharvester_1 python -m unittest discover
DEBUG:sfmutils.state_store:Setting state for weibo_harvester with key weibo.since_id to 3927348724716740
DEBUG:weibo_harvester:Harvest type is weibo_timeline
DEBUG:weibo_harvester:Processed 0 weibo
DEBUG:weibo_harvester:Searching since 3927348724716740 returned 1 weibo.
DEBUG:sfmutils.state_store:Setting state for weibo_harvester with key weibo.since_id to 3928235789939265
.DEBUG:weibo_harvester:Harvest type is weibo_timeline
DEBUG:weibo_harvester:Processed 0 weibo
DEBUG:weibo_harvester:Searching since None returned 2 weibo.
.FDEBUG:sfmutils.state_store:Setting state for weibo_harvester with key weibo.since_id to 3935747172100551
INFO:weibowarc:creating client session with api_key=131305798
DEBUG:weibo_harvester:Harvest type is weibo_timeline
INFO:weibowarc:starting search for max_id:None, since_id:3935747172100551.
EINFO:weibowarc:creating client session with api_key=131305798
DEBUG:weibo_harvester:Harvest type is weibo_timeline
INFO:weibowarc:starting search for max_id:None, since_id:None.
E
======================================================================
ERROR: test_incremental_search_vcr (tests.test_weibo_harvester.TestWeiboHarvesterVCR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/vcr/cassette.py", line 95, in __call__
    function, args, kwargs
  File "/usr/local/lib/python2.7/site-packages/vcr/cassette.py", line 103, in _execute_function
    return handler(function, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/vcr/cassette.py", line 130, in _handle_function
    return self.__handle_function(cassette, function, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/vcr/cassette.py", line 126, in __handle_function
    return function(*args, **kwargs)
  File "/opt/sfm-weibo-harvester/tests/test_weibo_harvester.py", line 61, in test_incremental_search_vcr
    self.harvester.harvest_seeds()
  File "/opt/sfm-weibo-harvester/weibo_harvester.py", line 26, in harvest_seeds
    self.search_timeline()
  File "/opt/sfm-weibo-harvester/weibo_harvester.py", line 35, in search_timeline
    max_weibo_id = self._process_weibos(self.weibowarc.search_friendships(since_id=since_id))
  File "/opt/sfm-weibo-harvester/weibo_harvester.py", line 51, in _process_weibos
    for count, weibo in enumerate(weibos):
  File "/opt/sfm-weibo-harvester/weibowarc.py", line 249, in search_friendships
    resp = self.get(friendships_url, **params)
  File "/opt/sfm-weibo-harvester/weibowarc.py", line 180, in new_f
    return fun(self, *args, **kwargs)
  File "/opt/sfm-weibo-harvester/weibowarc.py", line 283, in get
    return self.client.get(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/weibo.py", line 106, in get
    res = json.loads(self.session.get(url, params=kwargs).text)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/site-packages/vcr/stubs/__init__.py", line 236, in getresponse
    self.cassette.record_mode)
CannotOverwriteExistingCassetteException: No match for the request (<Request (GET) https://api.weibo.com/2/statuses/friends_timeline.json?access_token=2.00Hc6j5G09dwsI1b9fd5f627GSQXXB&count=100&page=1&since_id=3935747172100551>) was found. Can't overwrite existing cassette ('tests/fixtures/test_incremental_search_vcr') in your current record mode ('once').

======================================================================
ERROR: test_search_vcr (tests.test_weibo_harvester.TestWeiboHarvesterVCR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/vcr/cassette.py", line 95, in __call__
    function, args, kwargs
  File "/usr/local/lib/python2.7/site-packages/vcr/cassette.py", line 103, in _execute_function
    return handler(function, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/vcr/cassette.py", line 130, in _handle_function
    return self.__handle_function(cassette, function, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/vcr/cassette.py", line 126, in __handle_function
    return function(*args, **kwargs)
  File "/opt/sfm-weibo-harvester/tests/test_weibo_harvester.py", line 51, in test_search_vcr
    self.harvester.harvest_seeds()
  File "/opt/sfm-weibo-harvester/weibo_harvester.py", line 26, in harvest_seeds
    self.search_timeline()
  File "/opt/sfm-weibo-harvester/weibo_harvester.py", line 35, in search_timeline
    max_weibo_id = self._process_weibos(self.weibowarc.search_friendships(since_id=since_id))
  File "/opt/sfm-weibo-harvester/weibo_harvester.py", line 51, in _process_weibos
    for count, weibo in enumerate(weibos):
  File "/opt/sfm-weibo-harvester/weibowarc.py", line 249, in search_friendships
    resp = self.get(friendships_url, **params)
  File "/opt/sfm-weibo-harvester/weibowarc.py", line 180, in new_f
    return fun(self, *args, **kwargs)
  File "/opt/sfm-weibo-harvester/weibowarc.py", line 283, in get
    return self.client.get(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/weibo.py", line 106, in get
    res = json.loads(self.session.get(url, params=kwargs).text)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/site-packages/vcr/stubs/__init__.py", line 236, in getresponse
    self.cassette.record_mode)
CannotOverwriteExistingCassetteException: No match for the request (<Request (GET) https://api.weibo.com/2/statuses/friends_timeline.json?access_token=2.00Hc6j5G09dwsI1b9fd5f627GSQXXB&count=100&page=1>) was found. Can't overwrite existing cassette ('tests/fixtures/test_search_vcr') in your current record mode ('once').

======================================================================
FAIL: test_search (tests.test_weibo_harvester.TestWeiboHarvesterIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/sfm-weibo-harvester/tests/test_weibo_harvester.py", line 204, in test_search
    self.assertEqual("completed success", result_msg["status"])
AssertionError: 'completed success' != u'completed failure'

----------------------------------------------------------------------
Ran 5 tests in 0.674s

FAILED (failures=1, errors=2)
```

I will separately send you my credentials so that you can test.  If you need help with vcrpy let me know.

**Comment by Tanych** [comment]
@justinlittman  If I set the vcrpy record_mode with **once**, it would cause an error for new requests from different users if there is a cassette file.  If I set to **new_episodes**, all the assume tests would be fail.

**Comment by justinlittman** [comment]
You can:
1.  Create the cassette file as yourself.
2.  Change the test so that it uses hardcoded user credentials instead of
requiring that the user provide their own.
3.  Change the cassette file so that it matches those credentials.

That might not be entirely clear -- let me know if it is not.

**Comment by Tanych** [comment]
The up level API  [Weibo](https://github.com/lxyu/weibo) returns only with the JSON result data, not including all the requests data. 
```python
def get(self, uri, **kwargs):
        """Request resource by get method.
        """
        url = "{0}{1}.json".format(self.api_url, uri)

        # for username/password client auth
        if self.session.auth:
            kwargs['source'] = self.client_id

        res = json.loads(self.session.get(url, params=kwargs).text)
        self._assert_error(res)
        return res
```
Therefore, I can't check the status_code if the REST server not work well.
 I think it needs some improvement work on the [Weibo](https://github.com/lxyu/weibo)  that I am using right now.

**Comment by justinlittman** [comment]
Still seeing sending to real server:
```
 NFO:vcr.stubs:<Request (GET) https://api.weibo.com/2/statuses/friends_timeline.json?access_token=2.00Hc6j5G09dwsI1b9fd5f627GSQXXB&count=100&max_id=3952891964878100&page=1> not in cassette, sending to real server
```

vcrpy provides some options for matching:  https://vcrpy.readthedocs.org/en/latest/configuration.html#request-matching

**Comment by justinlittman** [comment]
When I run `docker-compose -f docker/dev.docker-compose.yml up -d`, I get following in logs:
```
sfmweiboharvester_1 | Traceback (most recent call last):
sfmweiboharvester_1 |   File "weibo_harvester.py", line 7, in <module>
sfmweiboharvester_1 |     from weiboarc import Weiboarc
sfmweiboharvester_1 |   File "/opt/sfm-weibo-harvester/weiboarc.py", line 12, in <module>
sfmweiboharvester_1 |     from twarc import load_config, default_config_filename, save_keys, get_input, catch_conn_reset
sfmweiboharvester_1 | ImportError: No module named twarc
```

**Comment by justinlittman** [comment]
`docker/dev/Dockerfile` references dev branch instead of master branch.

**Comment by justinlittman** [comment]
Pin version of rabbitmq in docker-compose files (like you do in ci.docker-compose.yml).

**Comment by justinlittman** [comment]
Deleted earlier comment about problem starting up containers in Docker.  I needed to do a docker-compose pull to get latest containers.

**Comment by justinlittman** [comment]
Comments on WeiboHarvester:
* At https://github.com/gwu-libraries/sfm-weibo-harvester/blob/master/weibo_harvester.py#L34, can do `"weibo.since_id"` instead of `"{}.since_id".format('weibo'))`.
* At https://github.com/gwu-libraries/sfm-weibo-harvester/blob/master/weibo_harvester.py#L54, checking for stop even not necessary since weibo isn't a stream (i.e., it stops when done not from a harvest stop message).

**Comment by justinlittman** [comment]
Comments on weiboarc.py:
* Since post not be used, post code should be removed. (Note that it will always be in the git history in case you need it later.)

**Comment by justinlittman** [comment]
Also, if `-s` is the only option (for now), don't make it a flag -- assume that will be doing a friendship timeline.

**Comment by justinlittman** [comment]
weiboarch.py uses twarcs configuration file by default, which means it will use twarcs values which don't work for weibo.  weiboarch's configuration file should be separate from twarcs so there is no interference.

**Comment by justinlittman** [comment]
For loading from the config file, use the keys that make sense for weibo (api key, api secret, access token, redirect uri), not the keys used by twarc for twitter.

**Comment by justinlittman** [comment]
If weiboarchtml is deprecated, then delete it.

**Comment by justinlittman** [comment]
README needs to specify what credentials are required for harvest start messages.

**Comment by justinlittman** [comment]
I've successfully:
* Requested a weibo harvest from SFM-UI
* Had that harvest performed by weibo harvester
* Gotten the status update in SFM-UI
* Iterated over the weibo posts in the WARC using weibo warc iter.

Awesome work @Tanych!

**Comment by kerchner** [comment]
:+1: !!

**Comment by Tanych** [comment]
@justinlittman  I will review the comments one by one! Thanks.

**Comment by justinlittman** [comment]
Just noticed that when you get and set state, it is global, not particular to an individual seed.

```
since_id = self.state_store.get_state(__name__, "weibo.since_id") if incremental else None
```

Thus, every harvest will share the same since_id.  Instead, this should be tied to the seed.

**Comment by justinlittman** [comment]
OK.  I've reviewed the changes.  I think all that needs to be done is fix the last comment and merge in the url extract pull request.

**Comment by Tanych** [comment]
@justinlittman  If I understand correctly, for the weibo harvester, I think we have talked about the seeds problem. The different seeds in the same collection should share the since_id, because weibo friendship timeline has no  search function based on the seeds.  For the different collection, they need to own their different since_id. I intended to consider that each collection will create their own harvester object. Right now, what I need to do is change the since_id based on the different collections.  AM I on the right way?

**Comment by justinlittman** [comment]
Collection isn't quite right, since a collection might have multiple weibo friendship seed sets.  It should really be the seed set.  However, the seed set is not passed to the harvester.

So I'd say go with the collection for now and create a ticket for switching to the seed set.

**Comment by Tanych** [comment]
Assume the haverser message like this:
```python
"id": "test:2",
"type": "weibo_timeline",
"seeds": [
	{
	    "token": "weibo1"
	},
	{
	    "token": "weibo2"
       }
],
"credentials": {
	"api_key": tests.WEIBO_API_KEY,
	"api_secret": tests.WEIBO_API_SECRET,
	"redirect_uri": tests.WEIBO_REDIRECT_URI,
	"access_token": tests.WEIBO_ACCESS_TOKEN
},
"collection": {
	"id": "test_collection",
	"path": "/collections/test_collection"
},
"options": {}

```
The seeds `weibo1` and `weibo2` should share the since_id, otherwise, they might archive the same data twice. At a very short time, the weibo friendship timeline returns the same results with the same starting since_id.

**Comment by kerchner** [comment]
Without #181, the only way to get sfm-ui to send a harvest.start message to sfm-weibo-harvester is to include dummy seed(s).

**Comment by kerchner** [comment]
Moving to 0.6 so that @justinlittman can review https://github.com/gwu-libraries/sfm-weibo-harvester/pull/9
