### ISSUE TITLE
Provided API credentials not valid for this type of API access

### ISSUE THREAD

**Issue by fishfree** [gwu-libraries/sfm-ui#1148]
My sfm-ui is v3.0.0, and the [docker-compose.yml](https://github.com/gwu-libraries/sfm-docker/blob/master/example.prod.docker-compose.yml) file.

I created a new twitter v2 API here:
![image](https://github.com/gwu-libraries/sfm-ui/assets/1741341/1a0dcd32-d719-41b2-915b-aa09796f7391)

I configured the v2 credential in the sfm-ui and created v2 search and user timeline seed, both returned the error as the title.

Part of the docker-compose logs is as below:
```
twitterpriorityrestharvester_1  | 2023-09-04 08:03:20,211: sfmutils.consumer --> Sending message to sfm_exchange with routing_key warc_created. The body is: {
twitterpriorityrestharvester_1  |     "harvest": {
twitterpriorityrestharvester_1  |         "id": "dba8533ce0094e35858758561695f31e",
twitterpriorityrestharvester_1  |         "type": "twitter_search"
twitterpriorityrestharvester_1  |     },
twitterpriorityrestharvester_1  |     "collection_set": {
twitterpriorityrestharvester_1  |         "id": "872fd1251694409a86d0b5fbc2c73bda"
twitterpriorityrestharvester_1  |     },
twitterpriorityrestharvester_1  |     "collection": {
twitterpriorityrestharvester_1  |         "id": "df156aa9c8e24e15a3472dca0c8fd940"
twitterpriorityrestharvester_1  |     },
twitterpriorityrestharvester_1  |     "warc": {
twitterpriorityrestharvester_1  |         "id": "c91c9e1464074b9a9221fbbeccc58d36",
twitterpriorityrestharvester_1  |         "path": "/sfm-collection-set-data/collection_set/872fd1251694409a86d0b5fbc2c73bda/df156aa9c8e24e15a3472dca0c8fd940/2023/09/04/00/dba8533ce0094e35858758561695f31e-20230904000318201-00000-2f41w5so.warc.gz",
twitterpriorityrestharvester_1  |         "date_created": "2023-09-04T08:03:20.206771+08:00",
twitterpriorityrestharvester_1  |         "bytes": 2083,
twitterpriorityrestharvester_1  |         "sha1": "97a02d17242c71c568a73f35b324843236a256c8"
twitterpriorityrestharvester_1  |     }
twitterpriorityrestharvester_1  | }
twitterpriorityrestharvester_1  | 2023-09-04 08:03:20,213: sfmutils.harvester --> Sending status message for harvest dba8533ce0094e35858758561695f31e: running
twitterpriorityrestharvester_1  | 2023-09-04 08:03:20,213: sfmutils.consumer --> Sending message to sfm_exchange with routing_key harvest.status.twitter.twitter_search.priority. The body is: {
twitterpriorityrestharvester_1  |     "id": "dba8533ce0094e35858758561695f31e",
twitterpriorityrestharvester_1  |     "status": "running",
twitterpriorityrestharvester_1  |     "infos": [],
twitterpriorityrestharvester_1  |     "warnings": [],
twitterpriorityrestharvester_1  |     "errors": [],
twitterpriorityrestharvester_1  |     "date_started": "2023-09-04T08:03:05.344264+08:00",
twitterpriorityrestharvester_1  |     "stats": {},
twitterpriorityrestharvester_1  |     "token_updates": {},
twitterpriorityrestharvester_1  |     "uids": {},
twitterpriorityrestharvester_1  |     "warcs": {
twitterpriorityrestharvester_1  |         "count": 2,
twitterpriorityrestharvester_1  |         "bytes": 4162
twitterpriorityrestharvester_1  |     },
twitterpriorityrestharvester_1  |     "service": "Twitter Harvester",
twitterpriorityrestharvester_1  |     "host": "a4b49b07d576",
twitterpriorityrestharvester_1  |     "instance": "1"
twitterpriorityrestharvester_1  | }
twitterpriorityrestharvester_1  | 2023-09-04 08:03:20,214: sfmutils.harvester --> Persisted result to /sfm-containers-data/containers/a4b49b07d576/dba8533ce0094e35858758561695f31e_result.json
twitterpriorityrestharvester_1  | 2023-09-04 08:03:20,215: sfmutils.harvester --> Waiting for processing to complete.
twitterpriorityrestharvester_1  | 2023-09-04 08:03:20,215: sfmutils.harvester --> Processing complete.
twitterpriorityrestharvester_1  | 2023-09-04 08:03:20,215: sfmutils.harvester --> Try 3 of 3
twitterpriorityrestharvester_1  | 2023-09-04 08:03:20,216: sfmutils.warcprox --> Executing warcprox -c /tmp/tmpw49tqn3g/warcprox-ca.pem --certs-dir /tmp/tmpw49tqn3g --dedup-db-file /dev/null --stats-db-file /dev/null -d /sfm-containers-data/containers/a4b49b07d576/tmp/dba8533ce0094e35858758561695f31e -n dba8533ce0094e35858758561695f31e -p 7408 -z --rollover-time 1800
twitterpriorityrestharvester_1  | 2023-09-04 08:03:20,968 3193 INFO MainThread root.stats_processor(controller.py:63) statistics tracking disabled
twitterpriorityrestharvester_1  | 2023-09-04 08:03:20,969 3193 INFO MainThread warcprox.warcproxy.WarcProxy.__init__(mitmproxy.py:558) 100 proxy threads
twitterpriorityrestharvester_1  | 2023-09-04 08:03:20,970 3193 INFO MainThread warcprox.warcproxy.WarcProxy.server_activate(warcproxy.py:532) listening on 127.0.0.1:7408
twitterpriorityrestharvester_1  | 2023-09-04 08:03:21,208 3193 INFO MainThread root.dedup_db(controller.py:52) deduplication disabled
twitterpriorityrestharvester_1  | 2023-09-04 08:03:21,209 3193 INFO WarcWriterProcessor warcprox.writerthread.WarcWriterProcessor._run(__init__.py:151) <WarcWriterProcessor(WarcWriterProcessor, started 140184976201472)> starting up
twitterpriorityrestharvester_1  | 2023-09-04 08:03:21,210 3193 INFO WarcWriterProcessor warcprox.writerthread.WarcWriterProcessor._startup(writerthread.py:57) 1 warc writer threads
twitterpriorityrestharvester_1  | 2023-09-04 08:03:21,210 3193 INFO RunningStats warcprox.BasePostfetchProcessor._run(__init__.py:151) <ListenerPostfetchProcessor(RunningStats, started 140184967808768)> starting up
twitterpriorityrestharvester_1  | 2023-09-04 08:03:25,225: __main__ --> Harvest type is twitter_search
twitterpriorityrestharvester_1  | 2023-09-04 08:03:25,225: twarc --> creating http session
twitterpriorityrestharvester_1  | 2023-09-04 08:03:25,226: root --> creating OAuth1 user authentication
twitterpriorityrestharvester_1  | 2023-09-04 08:03:25,226: twarc --> getting ('https://api.twitter.com/1.1/account/verify_credentials.json',) {'params': {'tweet_mode': 'extended'}}
twitterpriorityrestharvester_1  | 2023-09-04 08:03:25,520 3193 INFO WarcWriterThread(tid=3199) warcprox.writerthread.WarcWriterProcessor._log(writerthread.py:129) 127.0.0.1 401 GET https://api.twitter.com/1.1/account/verify_credentials.json?tweet_mode=extended application/json size=1162 - response dba8533ce0094e35858758561695f31e-20230904000325519-00000-cwxdgh1s.warc.gz offset=379
twitterpriorityrestharvester_1  | 2023-09-04 08:03:25,520: twarc --> 401 Authentication required for https://api.twitter.com/1.1/account/verify_credentials.json?tweet_mode=extended
twitterpriorityrestharvester_1  | 2023-09-04 08:03:25,521: sfmutils.warcprox --> Shutting down warcprox
twitterpriorityrestharvester_1  | 2023-09-04 08:03:25,521: sfmutils.warcprox --> Terminating warcprox
twitterpriorityrestharvester_1  | 2023-09-04 08:03:25,521: sfmutils.warcprox --> Waiting for warcprox to terminate
twitterpriorityrestharvester_1  | 2023-09-04 08:03:25,733 3193 INFO MainThread warcprox.warcproxy.WarcProxy.server_close(warcproxy.py:537) shutting down
twitterpriorityrestharvester_1  | 2023-09-04 08:03:26,018 3193 INFO WarcWriterProcessor warcprox.writerthread.WarcWriterProcessor._run(__init__.py:161) <WarcWriterProcessor(WarcWriterProcessor, started 140184976201472)> shutting down
twitterpriorityrestharvester_1  | 2023-09-04 08:03:26,021 3193 INFO RunningStats warcprox.BasePostfetchProcessor._run(__init__.py:161) <ListenerPostfetchProcessor(RunningStats, started 140184967808768)> shutting down
twitterpriorityrestharvester_1  | 2023-09-04 08:03:26,522: sfmutils.warcprox --> warcprox terminated
twitterpriorityrestharvester_1  | 2023-09-04 08:03:26,523: sfmutils.harvester --> Unknown error raised during harvest: Invalid credentials provided.
twitterpriorityrestharvester_1  | Traceback (most recent call last):
twitterpriorityrestharvester_1  |   File "/usr/local/lib/python3.8/site-packages/twarc/client.py", line 1011, in validate_keys
twitterpriorityrestharvester_1  |     self.get(url)
twitterpriorityrestharvester_1  |   File "/usr/local/lib/python3.8/site-packages/twarc/decorators.py", line 31, in new_f
twitterpriorityrestharvester_1  |     resp.raise_for_status()
twitterpriorityrestharvester_1  |   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
twitterpriorityrestharvester_1  |     raise HTTPError(http_error_msg, response=self)
twitterpriorityrestharvester_1  | requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.twitter.com/1.1/account/verify_credentials.json?tweet_mode=extended
twitterpriorityrestharvester_1  | This is a protected or locked account, or the credentials provided are no longer valid.
twitterpriorityrestharvester_1  | 
twitterpriorityrestharvester_1  | During handling of the above exception, another exception occurred:
twitterpriorityrestharvester_1  | 
twitterpriorityrestharvester_1  | Traceback (most recent call last):
twitterpriorityrestharvester_1  |   File "/opt/sfm-twitter-harvester/src/sfmutils/sfmutils/harvester.py", line 239, in on_message
twitterpriorityrestharvester_1  |     self.harvest_seeds()
twitterpriorityrestharvester_1  |   File "twitter_harvester.py", line 108, in harvest_seeds
twitterpriorityrestharvester_1  |     self._create_twarc()
twitterpriorityrestharvester_1  |   File "twitter_harvester.py", line 135, in _create_twarc
twitterpriorityrestharvester_1  |     self.twarc = Twarc(self.message["credentials"]["consumer_key"],
twitterpriorityrestharvester_1  |   File "/usr/local/lib/python3.8/site-packages/twarc/client.py", line 98, in __init__
twitterpriorityrestharvester_1  |     self.validate_keys()
twitterpriorityrestharvester_1  |   File "/usr/local/lib/python3.8/site-packages/twarc/client.py", line 1015, in validate_keys
twitterpriorityrestharvester_1  |     raise RuntimeError("Invalid credentials provided.")
twitterpriorityrestharvester_1  | RuntimeError: Invalid credentials provided.
```

Why?

**Comment by dolsysmith** [comment]
Just to clarify: what level of access did you sign up for when creating your v.2 credentials? As of now, Twitter/X does not permit harvesting Twitter data at the free level; it's necessary to upgrade to the [Basic](https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api) level in order to harvest Tweets. If you are using the API at the free level, I would expect your credentials not to work in SFM. 

Unfortunately, this is a restriction imposed by Twitter as of April 2023 (that free access no longer includes the ability to harvest Twitter data, only to create Tweets).

**Comment by fishfree** [comment]
@dolsysmith No wonder, OMG! Thank you!
