### ISSUE TITLE
create docker containers for sfm ui

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#21]

**Comment by justinlittman** [comment]
Suggest using the approach for containerizing a django app using for original social feed manager.

**Comment by justinlittman** [comment]
@rajatvij - I've updated the docker-compose in https://github.com/gwu-libraries/sfm-docker/tree/sfm_t21-docker_for_ui to instantiate the containers.  When I do, I get:
```
Waiting for db
python: can't open file '/opt/sfm-setup/appdeps.py': [Errno 2] No such file or directory
Updating requirements
Requirement already satisfied (use --upgrade to upgrade): django<=1.9,>=1.8 in /usr/local/lib/python2.7/dist-packages (from -r /opt/sfm-ui/requirements/requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/local/lib/python2.7/dist-packages (from -r /opt/sfm-ui/requirements/requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): psycopg2 in /usr/local/lib/python2.7/dist-packages (from -r /opt/sfm-ui/requirements/requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): django-allauth in /usr/local/lib/python2.7/dist-packages (from -r /opt/sfm-ui/requirements/requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): django-crispy-forms in /usr/local/lib/python2.7/dist-packages (from -r /opt/sfm-ui/requirements/requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): requests-oauthlib>=0.3.0 in /usr/local/lib/python2.7/dist-packages (from django-allauth->-r /opt/sfm-ui/requirements/requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): python-openid>=2.2.5 in /usr/local/lib/python2.7/dist-packages (from django-allauth->-r /opt/sfm-ui/requirements/requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): requests>=1.0.3 in /usr/lib/python2.7/dist-packages (from django-allauth->-r /opt/sfm-ui/requirements/requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): oauthlib>=0.6.2 in /usr/local/lib/python2.7/dist-packages (from requests-oauthlib>=0.3.0->django-allauth->-r /opt/sfm-ui/requirements/requirements.txt (line 4))
Writing local_settings
Copying config
cp: cannot stat '/tmp/wsgi.py': No such file or directory
Syncing db
/usr/local/lib/python2.7/dist-packages/django/core/management/commands/syncdb.py:24: RemovedInDjango19Warning: The syncdb command will be removed in Django 1.9
  warnings.warn("The syncdb command will be removed in Django 1.9", RemovedInDjango19Warning)

Traceback (most recent call last):
  File "/opt/sfm-ui/sfm/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 182, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 162, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

Migrating db
Traceback (most recent call last):
  File "/opt/sfm-ui/sfm/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 182, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 162, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

Running server
 * Starting web server apache2
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.8. Set the 'ServerName' directive globally to suppress this message
 * 
 * apache2 is running
Stopping server
 * Stopping web server apache2
 * 
 * apache2 is not running
Starting server again
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.8. Set the 'ServerName' directive globally to suppress this message
```

Looks like there may be a few problems:
* Can't find appdeps.py:  appdeps is now in pypi.  You can install with `pip install appdeps` and then invoke with `appdeps.py ...`.
* Can't copy wsgi.py:  You can remove this copy from invoke.sh.  It is only necessary when using a local copy of the code (e.g., for dev), not when a copy of the code is checked out from github.

I suspect that if you fix these the other problems will disappear.

**Comment by rajatvij** [comment]
@justinlittman Although i couldn't recreate the issue, but i have updated the relevant files and committed the changes as per your comment. Please check if you are experiencing the same problem again.

**Comment by justinlittman** [comment]
@rajatvij You want to use `appdeps.py`, not `python appdeps.py`.

```
bash-3.2$ docker exec -it sfmdocker_sfmui_1 /bin/bash
root@5f75f648d5f8:/opt/sfm-ui# python appdeps.py
python: can't open file 'appdeps.py': [Errno 2] No such file or directory
root@5f75f648d5f8:/opt/sfm-ui# appdeps.py
```

**Comment by rajatvij** [comment]
@justinlittman I have renamed the branch and updated invoke.sh file. If you need me to upload the images to gwul docker hub, then please let me know and i will update the branch according to that. Apologies, i forgot to ask about that before.

**Comment by justinlittman** [comment]
Can you go ahead and upload to images to your docker hub again and I will retest?

**Comment by rajatvij** [comment]
I uploaded images to my docker hub. You can test them.

**Comment by justinlittman** [comment]
OK.  I understand the confusion now.  Let's distinguish between 3 different flavors of a container:
* development:  Code is external to the container and linked in via a shared volume.
* master:  Master branch of code is added to the container at image build time.
* release:  Release of code is added to the container at image build time.

The Dockfile for SFM UI mixes development and master flavors.  The reason that it works with your docker-compose.yml is that you link in the external code, which replaces the included master branch of code.  It doesn't work with my docker-compose.yml because I don't link in the external code.

When the code is included in the image, all files must be included.  This requires adding some additional files like local_settings.py.  Also, there are differences in invoke.sh.

If you look closely at https://github.com/gwu-libraries/social-feed-manager/tree/t293-docker/docker, you should see these (slight) differences.

I suspect this still isn't sufficiently clear -- let's discuss.

**Comment by justinlittman** [comment]
Though not for a django app, https://github.com/gwu-libraries/sfm-flickr-harvester/tree/sfm_t22-flickr_harvester/docker demonstrates the difference between dev and master a bit more clearly.

**Comment by rajatvij** [comment]
I am getting confused. I think i included local_settings.py. I just changed its name to common.py. I guess i am missing something here. Let me know when we can discuss this.

**Comment by rajatvij** [comment]
I have committed the branch again with the changes we discussed today. Please check and let me know if there is anything else that is required there or if there is any issue with them. Please ignore Production environment in the branch for now as i have just used the same code or master in that just to have it in the same format as social feed manager's docker branch, which can be modified in future as per our requirement.

**Comment by dchud** [comment]
Pull request should have closed ticket, closing manually.
