### ISSUE TITLE
Flickr warc iter returns naive datetime

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#216]
Datetime must be aware.

This is causing exports limited by item date to fail with:
```
Traceback (most recent call last):
  File "flickr_exporter.py", line 44, in <module>
    FlickrExporter.main(FlickrExporter, QUEUE, [ROUTING_KEY])
  File "/opt/sfm-utils/sfmutils/exporter.py", line 231, in main
    exporter.run()
  File "/usr/local/lib/python2.7/site-packages/kombu/mixins.py", line 177, in run
    for _ in self.consume(limit=None):  # pragma: no cover
  File "/usr/local/lib/python2.7/site-packages/kombu/mixins.py", line 199, in consume
    conn.drain_events(timeout=safety_interval)
  File "/usr/local/lib/python2.7/site-packages/librabbitmq/__init__.py", line 220, in drain_events
    self._basic_recv(timeout)
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 598, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 564, in receive
    [callback(body, message) for callback in callbacks]
  File "/opt/sfm-utils/sfmutils/consumer.py", line 121, in _callback
    self.on_message()
  File "/opt/sfm-utils/sfmutils/exporter.py", line 102, in on_message
    export_formats[export_format][1](table, filepath)
  File "/usr/local/lib/python2.7/site-packages/petl/io/csv.py", line 107, in tocsv
    write_header=write_header, **csvargs)
  File "/usr/local/lib/python2.7/site-packages/petl/io/csv_py2.py", line 50, in tocsv_impl
    _writecsv(table, source=source, mode='wb', **kwargs)
  File "/usr/local/lib/python2.7/site-packages/petl/io/csv_py2.py", line 74, in _writecsv
    for row in rows:
  File "/opt/sfm-utils/sfmutils/exporter.py", line 277, in __iter__
    item_date_end=self.item_date_end):
  File "/opt/sfm-utils/sfmutils/warc_iter.py", line 72, in iter
    if item_date_start and item_date and item_date < item_date_start:
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-flickr-harvester/commit/ddbf2536ce49f8c9e87cff7b923aebd51cb6205b.

Also added test to twitter rest warc iter.
