### ISSUE TITLE
Warcprox doesn't handle read timeouts

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#217]
Currently, I'm seeing instances where warcprox gets a read timeout from the Twitter API when performing a search.  That seems to result in an incomplete record being sent to Twarc, which fails on parsing the invalid JSON.

Instead, warcprox when a read timeout is encountered, warcprox should block on the write to the client to force it to timeout as well. (I think.)

This may require creating a fake web server that writes and then blocks for testing.

**Comment by kerchner** [comment]
Hasn't been an issue lately.  Closing.

**Comment by kerchner** [comment]
Something similar to this seems to have happened again (on the EOT instance).   @justinlittman does this look like what you were seeing?

```
twitterrestharvester_1    | 2016-11-08 15:28:03,524: requests.packages.urllib3.connectionpool --> Resetting dropped connection: api.twitter.com
twitterrestharvester_1    | 2016-11-08 15:28:03,524: requests.packages.urllib3.connectionpool --> Starting new HTTPS connection (505): api.twitter.com
twitterrestharvester_1    | 2016-11-08 15:28:03,566 23534 INFO WarcWriterThread warcprox.warcwriter.WarcWriterThread.run(warcwriter.py:292) recorded_url.warcprox_meta={} for https://api.twitter.com/1.1/statuses/user_timeline.json?count=200&user_id=264303278&since_id=515131443971112962
twitterrestharvester_1    | 2016-11-08 15:28:03,568 23534 INFO Thread-505 warcprox.warcprox.WarcProxyHandler.log_message(mitmproxy.py:147) WarcProxyHandler localhost - - [08/Nov/2016 15:28:03] "CONNECT api.twitter.com:443 HTTP/1.0" 200 -
twitterrestharvester_1    | Traceback (most recent call last):
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/SocketServer.py", line 599, in process_request_thread
twitterrestharvester_1    |     self.finish_request(request, client_address)
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/SocketServer.py", line 334, in finish_request
twitterrestharvester_1    |     self.RequestHandlerClass(request, client_address, self)
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/site-packages/warcprox/warcprox.py", line 158, in __init__
twitterrestharvester_1    |     warcprox.mitmproxy.MitmProxyHandler.__init__(self, request, client_address, server)
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/site-packages/warcprox/mitmproxy.py", line 25, in __init__
twitterrestharvester_1    |     http_server.BaseHTTPRequestHandler.__init__(self, request, client_address, server)
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/SocketServer.py", line 655, in __init__
twitterrestharvester_1    |     self.handle()
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
twitterrestharvester_1    |     self.handle_one_request()
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
twitterrestharvester_1    |     method()
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/site-packages/warcprox/mitmproxy.py", line 96, in do_CONNECT
twitterrestharvester_1    |     self.handle_one_request()
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
twitterrestharvester_1    |     method()
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/site-packages/warcprox/mitmproxy.py", line 131, in do_COMMAND
twitterrestharvester_1    |     self._proxy_request()
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/site-packages/warcprox/warcprox.py", line 204, in _proxy_request
twitterrestharvester_1    |     buf = h.read(8192)
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/httplib.py", line 612, in read
twitterrestharvester_1    |     s = self.fp.read(amt)
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/site-packages/warcprox/warcprox.py", line 113, in read
twitterrestharvester_1    |     hunk = self.fp.read(size)
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/socket.py", line 384, in read
twitterrestharvester_1    |     data = self._sock.recv(left)
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/ssl.py", line 734, in recv
twitterrestharvester_1    |     return self.read(buflen)
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/ssl.py", line 621, in read
twitterrestharvester_1    |     v = self._sslobj.read(len or 1024)
twitterrestharvester_1    | SSLError: ('The read operation timed out',)
twitterrestharvester_1    | 2016-11-08 15:29:03,712: sfmutils.warcprox --> Shutting down warcprox
twitterrestharvester_1    | 2016-11-08 15:29:03,712: sfmutils.warcprox --> Terminating warcprox
twitterrestharvester_1    | 2016-11-08 15:29:03,712: sfmutils.warcprox --> Waiting for warcprox to terminate
twitterrestharvester_1    | ----------------------------------------
twitterrestharvester_1    | Exception happened during processing of request from ('127.0.0.1', 44259)
twitterrestharvester_1    | ----------------------------------------
twitterrestharvester_1    | 2016-11-08 15:29:04,103 23534 INFO MainThread warcprox.warcprox.WarcProxy.server_close(warcprox.py:306) WarcProxy shutting down
twitterrestharvester_1    | 2016-11-08 15:29:04,591 23534 INFO WarcWriterThread warcprox.warcwriter.WarcWriterThread.run(warcwriter.py:317) WarcWriterThread shutting down
twitterrestharvester_1    | 2016-11-08 15:29:04,592 23534 INFO WarcWriterThread warcprox.warcwriter.WarcWriter.close_writer(warcwriter.py:168) closing 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz
twitterrestharvester_1    | 2016-11-08 15:29:04,607: sfmutils.warcprox --> warcprox terminated
twitterrestharvester_1    | 2016-11-08 15:29:04,607: sfmutils.harvester --> Unknown error raised during harvest: No JSON object could be decoded
twitterrestharvester_1    | Traceback (most recent call last):
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/site-packages/sfmutils/harvester.py", line 226, in on_message
twitterrestharvester_1    |     self.harvest_seeds()
twitterrestharvester_1    |   File "twitter_harvester.py", line 52, in harvest_seeds
twitterrestharvester_1    |     self.user_timeline()
twitterrestharvester_1    |   File "twitter_harvester.py", line 108, in user_timeline
twitterrestharvester_1    |     new_screen_name = self._lookup_screen_name(user_id)
twitterrestharvester_1    |   File "twitter_harvester.py", line 134, in _lookup_screen_name
twitterrestharvester_1    |     users = list(self.twarc.user_lookup(user_ids=(user_id,)))
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/site-packages/twarc.py", line 489, in user_lookup
twitterrestharvester_1    |     users = resp.json()
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 808, in json
twitterrestharvester_1    |     return complexjson.loads(self.text, **kwargs)
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
twitterrestharvester_1    |     return _default_decoder.decode(s)
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
twitterrestharvester_1    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
twitterrestharvester_1    |   File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
twitterrestharvester_1    |     raise ValueError("No JSON object could be decoded")
twitterrestharvester_1    | ValueError: No JSON object could be decoded
twitterrestharvester_1    | 2016-11-08 15:29:04,608: sfmutils.harvester --> Too many retries, so giving up on harvesting seeds.
twitterrestharvester_1    | 2016-11-08 15:29:04,608: sfmutils.harvester --> Queueing WARC files
twitterrestharvester_1    | 2016-11-08 15:29:04,608: sfmutils.harvester --> Found following WARCs: [u'9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz']
twitterrestharvester_1    | 2016-11-08 15:29:04,608: sfmutils.harvester --> Queueing 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz
twitterrestharvester_1    | 2016-11-08 15:29:04,608: sfmutils.harvester --> Waiting for processing to complete.
twitterrestharvester_1    | 2016-11-08 15:29:04,645: sfmutils.harvester --> Processing 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz
twitterrestharvester_1    | 2016-11-08 15:29:04,645: __main__ --> Harvest type is twitter_user_timeline
twitterrestharvester_1    | 2016-11-08 15:29:04,645: sfmutils.warc_iter --> Iterating over /sfm-data/containers/21489fca2bee/tmp/9f0cd3ca81374d3e98581cde8f9e24ce/9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz
twitterrestharvester_1    | 2016-11-08 15:29:04,646: sfmutils.warc_iter --> File 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz. Processed 0 records. Yielded 0 items.
twitterrestharvester_1    | 2016-11-08 15:29:04,651: __main__ --> Processing 0 tweets
twitterrestharvester_1    | 2016-11-08 15:29:04,655: sfmutils.state_store --> Setting state for __main__ with key timeline.200213729.since_id to 796084433950371840
twitterrestharvester_1    | 2016-11-08 15:29:04,655: sfmutils.state_store --> Setting state for __main__ with key timeline.200213729.since_id to 796084433950371840
twitterrestharvester_1    | 2016-11-08 15:29:04,657: sfmutils.warc_iter --> File 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz. Processed 10 records. Yielded 2 items.
twitterrestharvester_1    | 2016-11-08 15:29:04,662: sfmutils.warc_iter --> File 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz. Processed 20 records. Yielded 2 items.
twitterrestharvester_1    | 2016-11-08 15:29:04,667: sfmutils.warc_iter --> File 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz. Processed 30 records. Yielded 2 items.
twitterrestharvester_1    | 2016-11-08 15:29:04,672: sfmutils.warc_iter --> File 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz. Processed 40 records. Yielded 2 items.
twitterrestharvester_1    | 2016-11-08 15:29:04,677: sfmutils.warc_iter --> File 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz. Processed 50 records. Yielded 2 items.
twitterrestharvester_1    | 2016-11-08 15:29:04,682: sfmutils.state_store --> Setting state for __main__ with key timeline.113605440.since_id to 796084553974747137
twitterrestharvester_1    | 2016-11-08 15:29:04,686: sfmutils.warc_iter --> File 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz. Processed 60 records. Yielded 3 items.
twitterrestharvester_1    | 2016-11-08 15:29:04,691: sfmutils.warc_iter --> File 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz. Processed 70 records. Yielded 3 items.
twitterrestharvester_1    | 2016-11-08 15:29:04,696: sfmutils.warc_iter --> File 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz. Processed 80 records. Yielded 3 items.
twitterrestharvester_1    | 2016-11-08 15:29:04,701: sfmutils.warc_iter --> File 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz. Processed 90 records. Yielded 3 items.
twitterrestharvester_1    | 2016-11-08 15:29:04,707: sfmutils.state_store --> Setting state for __main__ with key timeline.976538112.since_id to 796084046455599104
twitterrestharvester_1    | 2016-11-08 15:29:04,709: sfmutils.warc_iter --> File 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz. Processed 100 records. Yielded 4 items.
twitterrestharvester_1    | 2016-11-08 15:29:04,740: sfmutils.state_store --> Setting state for __main__ with key timeline.606625312.since_id to 796080131269750784
twitterrestharvester_1    | 2016-11-08 15:29:04,740: sfmutils.state_store --> Setting state for __main__ with key timeline.606625312.since_id to 796080131269750784
twitterrestharvester_1    | 2016-11-08 15:29:04,746: sfmutils.state_store --> Setting state for __main__ with key timeline.48074218.since_id to 796083696562532356
twitterrestharvester_1    | 2016-11-08 15:29:04,760: sfmutils.state_store --> Setting state for __main__ with key timeline.119166791.since_id to 796082224181428230
twitterrestharvester_1    | 2016-11-08 15:29:04,760: sfmutils.state_store --> Setting state for __main__ with key timeline.119166791.since_id to 796082224181428230
twitterrestharvester_1    | 2016-11-08 15:29:04,770: sfmutils.warc_iter --> File 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz. Processed 200 records. Yielded 9 items.
twitterrestharvester_1    | 2016-11-08 15:29:04,808: sfmutils.state_store --> Setting state for __main__ with key timeline.246961538.since_id to 796081245692329986
twitterrestharvester_1    | 2016-11-08 15:29:04,823: sfmutils.warc_iter --> File 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz. Processed 300 records. Yielded 10 items.
twitterrestharvester_1    | 2016-11-08 15:29:04,836: sfmutils.state_store --> Setting state for __main__ with key timeline.2724146642.since_id to 796082537403662336
twitterrestharvester_1    | 2016-11-08 15:29:04,859: sfmutils.state_store --> Setting state for __main__ with key timeline.1307544762.since_id to 796081075713900544
twitterrestharvester_1    | 2016-11-08 15:29:04,882: sfmutils.warc_iter --> File 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz. Processed 400 records. Yielded 12 items.
twitterrestharvester_1    | 2016-11-08 15:29:04,912: sfmutils.state_store --> Setting state for __main__ with key timeline.1089287436.since_id to 796084874063085568
twitterrestharvester_1    | 2016-11-08 15:29:04,937: sfmutils.warc_iter --> File 9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz. Processed 500 records. Yielded 13 items.
twitterrestharvester_1    | 2016-11-08 15:29:04,939: sfmutils.harvester --> No urls, so not sending a web harvest message.
twitterrestharvester_1    | 2016-11-08 15:29:04,939: sfmutils.harvester --> Moving /sfm-data/containers/21489fca2bee/tmp/9f0cd3ca81374d3e98581cde8f9e24ce/9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz to /sfm-data/collection_set/3354aac8b3bd40ef940479bb4310d9d7/1389c48220fb4ca380a368e4bb4f1495/2016/11/08/20/9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz
twitterrestharvester_1    | 2016-11-08 15:29:04,942: sfmutils.state_store --> Setting state for __main__ with key timeline.2724146642.since_id to 796082537403662336
twitterrestharvester_1    | 2016-11-08 15:29:04,964: sfmutils.state_store --> Setting state for __main__ with key timeline.976538112.since_id to 796084046455599104
twitterrestharvester_1    | 2016-11-08 15:29:04,986: sfmutils.state_store --> Setting state for __main__ with key timeline.113605440.since_id to 796084553974747137
twitterrestharvester_1    | 2016-11-08 15:29:05,008: sfmutils.state_store --> Setting state for __main__ with key timeline.119166791.since_id to 796082224181428230
twitterrestharvester_1    | 2016-11-08 15:29:05,030: sfmutils.state_store --> Setting state for __main__ with key timeline.1307544762.since_id to 796081075713900544
twitterrestharvester_1    | 2016-11-08 15:29:05,052: sfmutils.state_store --> Setting state for __main__ with key timeline.606625312.since_id to 796080131269750784
twitterrestharvester_1    | 2016-11-08 15:29:05,074: sfmutils.state_store --> Setting state for __main__ with key timeline.48074218.since_id to 796083696562532356
twitterrestharvester_1    | 2016-11-08 15:29:05,095: sfmutils.state_store --> Setting state for __main__ with key timeline.246961538.since_id to 796081245692329986
twitterrestharvester_1    | 2016-11-08 15:29:05,117: sfmutils.state_store --> Setting state for __main__ with key timeline.1089287436.since_id to 796084874063085568
twitterrestharvester_1    | 2016-11-08 15:29:05,138: sfmutils.state_store --> Setting state for __main__ with key timeline.200213729.since_id to 796084433950371840
twitterrestharvester_1    | 2016-11-08 15:29:05,161: sfmutils.consumer --> Sending message to sfm_exchange with routing_key warc_created. The body is: {
twitterrestharvester_1    |     "collection_set": {
twitterrestharvester_1    |         "id": "3354aac8b3bd40ef940479bb4310d9d7"
twitterrestharvester_1    |     }, 
twitterrestharvester_1    |     "harvest": {
twitterrestharvester_1    |         "type": "twitter_user_timeline", 
twitterrestharvester_1    |         "id": "9f0cd3ca81374d3e98581cde8f9e24ce"
twitterrestharvester_1    |     }, 
twitterrestharvester_1    |     "warc": {
twitterrestharvester_1    |         "path": "/sfm-data/collection_set/3354aac8b3bd40ef940479bb4310d9d7/1389c48220fb4ca380a368e4bb4f1495/2016/11/08/20/9f0cd3ca81374d3e98581cde8f9e24ce-20161108202656551-00000-23534-21489fca2bee-8000.warc.gz", 
twitterrestharvester_1    |         "sha1": "4ac49d884dfd18c93933ea4609ae86bd50e01110", 
twitterrestharvester_1    |         "bytes": 1193898, 
twitterrestharvester_1    |         "id": "8eef2582ca294efc81528e806c8a8648", 
twitterrestharvester_1    |         "date_created": "2016-11-08T15:29:04.936234"
twitterrestharvester_1    |     }
twitterrestharvester_1    | }
twitterrestharvester_1    | 2016-11-08 15:29:05,161: sfmutils.consumer --> Sending message to sfm_exchange with routing_key harvest.status.twitter.twitter_user_timeline. The body is: {
twitterrestharvester_1    |     "status": "running", 
twitterrestharvester_1    |     "errors": [
twitterrestharvester_1    |         {
twitterrestharvester_1    |             "message": "No JSON object could be decoded", 
twitterrestharvester_1    |             "code": "unknown_error"
twitterrestharvester_1    |         }
twitterrestharvester_1    |     ], 
twitterrestharvester_1    |     "stats": {
twitterrestharvester_1    |         "2016-11-08": {
twitterrestharvester_1    |             "tweets": 8216
twitterrestharvester_1    |         }
twitterrestharvester_1    |     }, 
twitterrestharvester_1    |     "uids": {}, 
twitterrestharvester_1    |     "warnings": [
twitterrestharvester_1    |         {
twitterrestharvester_1    |             "message": "Unauthorized for user None because account is suspended or private", 
twitterrestharvester_1    |             "code": "token_unauthorized"
twitterrestharvester_1    |         }, 
twitterrestharvester_1    |         {
twitterrestharvester_1    |             "message": "Unauthorized for user None because account is suspended or private", 
twitterrestharvester_1    |             "code": "token_unauthorized"
twitterrestharvester_1    |         }
twitterrestharvester_1    |     ], 
twitterrestharvester_1    |     "token_updates": {}, 
twitterrestharvester_1    |     "infos": [], 
twitterrestharvester_1    |     "date_started": "2016-11-08T14:40:18.377011", 
twitterrestharvester_1    |     "id": "9f0cd3ca81374d3e98581cde8f9e24ce", 
twitterrestharvester_1    |     "warcs": {
twitterrestharvester_1    |         "count": 3, 
twitterrestharvester_1    |         "bytes": 16248841
twitterrestharvester_1    |     }
twitterrestharvester_1    | }
twitterrestharvester_1    | 2016-11-08 15:29:05,162: sfmutils.harvester --> Persisted result to /sfm-data/containers/21489fca2bee/9f0cd3ca81374d3e98581cde8f9e24ce_result.json
twitterrestharvester_1    | 2016-11-08 15:29:05,163: sfmutils.harvester --> Processing complete.
twitterrestharvester_1    | 2016-11-08 15:29:05,163: sfmutils.consumer --> Sending message to sfm_exchange with routing_key harvest.status.twitter.twitter_user_timeline. The body is: {
twitterrestharvester_1    |     "status": "completed failure", 
twitterrestharvester_1    |     "warnings": [
twitterrestharvester_1    |         {
twitterrestharvester_1    |             "message": "Unauthorized for user None because account is suspended or private", 
twitterrestharvester_1    |             "code": "token_unauthorized"
twitterrestharvester_1    |         }, 
twitterrestharvester_1    |         {
twitterrestharvester_1    |             "message": "Unauthorized for user None because account is suspended or private", 
twitterrestharvester_1    |             "code": "token_unauthorized"
twitterrestharvester_1    |         }
twitterrestharvester_1    |     ], 
twitterrestharvester_1    |     "infos": [], 
twitterrestharvester_1    |     "id": "9f0cd3ca81374d3e98581cde8f9e24ce", 
twitterrestharvester_1    |     "errors": [
twitterrestharvester_1    |         {
twitterrestharvester_1    |             "message": "No JSON object could be decoded", 
twitterrestharvester_1    |             "code": "unknown_error"
twitterrestharvester_1    |         }
twitterrestharvester_1    |     ], 
twitterrestharvester_1    |     "stats": {
twitterrestharvester_1    |         "2016-11-08": {
twitterrestharvester_1    |             "tweets": 8216
twitterrestharvester_1    |         }
twitterrestharvester_1    |     }, 
twitterrestharvester_1    |     "uids": {}, 
twitterrestharvester_1    |     "token_updates": {}, 
twitterrestharvester_1    |     "date_ended": "2016-11-08T15:29:05.163440", 
twitterrestharvester_1    |     "date_started": "2016-11-08T14:40:18.377011", 
twitterrestharvester_1    |     "warcs": {
twitterrestharvester_1    |         "count": 3, 
twitterrestharvester_1    |         "bytes": 16248841
twitterrestharvester_1    |     }
twitterrestharvester_1    | }
twitterrestharvester_1    | 2016-11-08 15:29:05,164: sfmutils.consumer --> Deleted /sfm-data/containers/21489fca2bee/last_message.json
```

Thus ended the harvest.   A subsequent, new harvest seemed to succeed, without having to reset/restart anything on the back end.
