### ISSUE TITLE
Yahoo sending mail fails with SMTPSenderRefused

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-ui#250]
### Sign up Info
- Name: Victor
- Email: tanych5233@hotmail.com
### SFM App Info
- SFM_EMAIL_USER: tanych5233@yahoo.com
- SFM_SMTP_HOST: smtp.mail.yahoo.com
### Error Info

``` python
(501, 'Syntax error in arguments', u'webmaster@localhost')
Request Method: POST
Request URL:    http://localhost:8080/accounts/signup/
Django Version: 1.8.8
Exception Type: SMTPSenderRefused
Exception Value:    
(501, 'Syntax error in arguments', u'webmaster@localhost')
Exception Location: /usr/lib/python2.7/smtplib.py in sendmail, line 731
Python Executable:  /usr/bin/python
Python Version: 2.7.6
Python Path:    
['/opt/sfm-ui/sfm',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
Server time:    Wed, 11 May 2016 16:08:35 -0500
```
### SFM Logs

``` python
sfmdevapp_1         | [Wed May 11 16:08:35.890025 2016] [:error] [pid 217:tid 140366736254720] ERROR 2016-05-11 16:08:35,888 217 django.request Internal Server Error: /accounts/signup/
sfmdevapp_1         | [Wed May 11 16:08:35.890028 2016] [:error] [pid 217:tid 140366736254720] Traceback (most recent call last):
sfmdevapp_1         | [Wed May 11 16:08:35.890029 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
sfmdevapp_1         | [Wed May 11 16:08:35.890030 2016] [:error] [pid 217:tid 140366736254720]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
sfmdevapp_1         | [Wed May 11 16:08:35.890031 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
sfmdevapp_1         | [Wed May 11 16:08:35.890032 2016] [:error] [pid 217:tid 140366736254720]     return self.dispatch(request, *args, **kwargs)
sfmdevapp_1         | [Wed May 11 16:08:35.890033 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 34, in _wrapper
sfmdevapp_1         | [Wed May 11 16:08:35.890034 2016] [:error] [pid 217:tid 140366736254720]     return bound_func(*args, **kwargs)
sfmdevapp_1         | [Wed May 11 16:08:35.890035 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
sfmdevapp_1         | [Wed May 11 16:08:35.890036 2016] [:error] [pid 217:tid 140366736254720]     return view(request, *args, **kwargs)
sfmdevapp_1         | [Wed May 11 16:08:35.890037 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 30, in bound_func
sfmdevapp_1         | [Wed May 11 16:08:35.890038 2016] [:error] [pid 217:tid 140366736254720]     return func.__get__(self, type(self))(*args2, **kwargs2)
sfmdevapp_1         | [Wed May 11 16:08:35.890038 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/allauth/account/views.py", line 174, in dispatch
sfmdevapp_1         | [Wed May 11 16:08:35.890039 2016] [:error] [pid 217:tid 140366736254720]     return super(SignupView, self).dispatch(request, *args, **kwargs)
sfmdevapp_1         | [Wed May 11 16:08:35.890040 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/allauth/account/views.py", line 69, in dispatch
sfmdevapp_1         | [Wed May 11 16:08:35.890041 2016] [:error] [pid 217:tid 140366736254720]     **kwargs)
sfmdevapp_1         | [Wed May 11 16:08:35.890042 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/allauth/account/views.py", line 152, in dispatch
sfmdevapp_1         | [Wed May 11 16:08:35.890043 2016] [:error] [pid 217:tid 140366736254720]     **kwargs)
sfmdevapp_1         | [Wed May 11 16:08:35.890044 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
sfmdevapp_1         | [Wed May 11 16:08:35.890046 2016] [:error] [pid 217:tid 140366736254720]     return handler(request, *args, **kwargs)
sfmdevapp_1         | [Wed May 11 16:08:35.890047 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/allauth/account/views.py", line 85, in post
sfmdevapp_1         | [Wed May 11 16:08:35.890048 2016] [:error] [pid 217:tid 140366736254720]     response = self.form_valid(form)
sfmdevapp_1         | [Wed May 11 16:08:35.890050 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/allauth/account/views.py", line 190, in form_valid
sfmdevapp_1         | [Wed May 11 16:08:35.890051 2016] [:error] [pid 217:tid 140366736254720]     self.get_success_url())
sfmdevapp_1         | [Wed May 11 16:08:35.890052 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/allauth/account/utils.py", line 167, in complete_signup
sfmdevapp_1         | [Wed May 11 16:08:35.890054 2016] [:error] [pid 217:tid 140366736254720]     signal_kwargs=signal_kwargs)
sfmdevapp_1         | [Wed May 11 16:08:35.890054 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/allauth/account/utils.py", line 128, in perform_login
sfmdevapp_1         | [Wed May 11 16:08:35.890055 2016] [:error] [pid 217:tid 140366736254720]     send_email_confirmation(request, user, signup=signup)
sfmdevapp_1         | [Wed May 11 16:08:35.890056 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/allauth/account/utils.py", line 296, in send_email_confirmation
sfmdevapp_1         | [Wed May 11 16:08:35.890057 2016] [:error] [pid 217:tid 140366736254720]     signup=signup)
sfmdevapp_1         | [Wed May 11 16:08:35.890058 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/allauth/account/models.py", line 58, in send_confirmation
sfmdevapp_1         | [Wed May 11 16:08:35.890059 2016] [:error] [pid 217:tid 140366736254720]     confirmation.send(request, signup=signup)
sfmdevapp_1         | [Wed May 11 16:08:35.890060 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/allauth/account/models.py", line 122, in send
sfmdevapp_1         | [Wed May 11 16:08:35.890063 2016] [:error] [pid 217:tid 140366736254720]     get_adapter().send_confirmation_mail(request, self, signup)
sfmdevapp_1         | [Wed May 11 16:08:35.890064 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/allauth/account/adapter.py", line 369, in send_confirmation_mail
sfmdevapp_1         | [Wed May 11 16:08:35.890065 2016] [:error] [pid 217:tid 140366736254720]     ctx)
sfmdevapp_1         | [Wed May 11 16:08:35.890066 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/allauth/account/adapter.py", line 110, in send_mail
sfmdevapp_1         | [Wed May 11 16:08:35.890068 2016] [:error] [pid 217:tid 140366736254720]     msg.send()
sfmdevapp_1         | [Wed May 11 16:08:35.890069 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/django/core/mail/message.py", line 303, in send
sfmdevapp_1         | [Wed May 11 16:08:35.890069 2016] [:error] [pid 217:tid 140366736254720]     return self.get_connection(fail_silently).send_messages([self])
sfmdevapp_1         | [Wed May 11 16:08:35.890071 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/smtp.py", line 107, in send_messages
sfmdevapp_1         | [Wed May 11 16:08:35.890072 2016] [:error] [pid 217:tid 140366736254720]     sent = self._send(message)
sfmdevapp_1         | [Wed May 11 16:08:35.890073 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/smtp.py", line 123, in _send
sfmdevapp_1         | [Wed May 11 16:08:35.890074 2016] [:error] [pid 217:tid 140366736254720]     self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\\r\\n'))
sfmdevapp_1         | [Wed May 11 16:08:35.890076 2016] [:error] [pid 217:tid 140366736254720]   File "/usr/lib/python2.7/smtplib.py", line 731, in sendmail
sfmdevapp_1         | [Wed May 11 16:08:35.890077 2016] [:error] [pid 217:tid 140366736254720]     raise SMTPSenderRefused(code, resp, from_addr)
sfmdevapp_1         | [Wed May 11 16:08:35.890078 2016] [:error] [pid 217:tid 140366736254720] SMTPSenderRefused: (501, 'Syntax error in arguments', u'webmaster@localhost')

```

**Comment by kerchner** [comment]
@Tanych Is this still occurring now that #248 has been merged in?

**Comment by Tanych** [comment]
@kerchner  I have retested the merged code. It doesn't occur this issue. This can be closed.

**Comment by kerchner** [comment]
Thank you @Tanych !  Closing the issue.

**Comment by Tanych** [comment]
For this issue, `.env` as follows:
SFM_SMTP_HOST=smtp.mail.yahoo.com
SFM_EMAIL_USER=tanych5233@yahoo.com
SFM_EMAIL_PASSWORD=[my password, confirm it's correct]
Also, try to modify the SMPT port to `465` or `587`. Both of them are not working.

**Comment by justinlittman** [comment]
Gmail is supported, which is OK for now.
