### ISSUE TITLE
test_login smoke test fails

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#289]
```
======================================================================
ERROR: test_login (smoke_tests.test_ui.UiSmokeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/sfm-test/smoke_tests/test_ui.py", line 18, in test_login
    browser.find_by_css(".primaryAction").click()
  File "/usr/local/lib/python2.7/site-packages/splinter/element_list.py", line 75, in __getattr__
    self.__class__.__name__, name))
AttributeError: 'ElementList' object has no attribute 'click'

----------------------------------------------------------------------
Ran 5 tests in 16.729s

FAILED (errors=1)
http://mq:15672/api/whoami
http://mq:15672/api/aliveness-test/%2F
http://mq:15672/api/exchanges
http://mq:15672/api/whoami
http://mq:15672/api/aliveness-test/%2F
http://mq:15672/api/queues
```

**Comment by justinlittman** [comment]
So I think this will be fixed when the new smoke test container is built.

**Comment by kerchner** [comment]
@kerchner to follow directions in sfm-docker README to stand up a smoke test container, and close this issue if it doesn't occur there.

**Comment by kerchner** [comment]
Re-ran according to sfm-docker README; no issues.  Closing ticket.
