### ISSUE TITLE
Heritrix error

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#296]
Getting:
```
UNREGISTERED FOR KRYO class java.util.LinkedHashSet in class org.archive.modules.CrawlURI
2016-06-01 17:12:55.415 WARNING thread-38 org.archive.modules.extractor.ExtractorHTML.innerExtract() Failed get of replay char sequence in ToeThread #2: http://www.wral.com/blue-cross-to-reveal-2015-health-insurance-rates/14102936/
java.io.IOException: chunked stream ended unexpectedly
	at org.apache.commons.httpclient.ChunkedInputStream.getChunkSizeFromInputStream(ChunkedInputStream.java:252)
	at org.apache.commons.httpclient.ChunkedInputStream.nextChunk(ChunkedInputStream.java:221)
	at org.apache.commons.httpclient.ChunkedInputStream.read(ChunkedInputStream.java:176)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.read1(BufferedReader.java:203)
	at java.io.BufferedReader.read(BufferedReader.java:279)
	at java.io.Reader.read(Reader.java:100)
	at org.archive.io.GenericReplayCharSequence.decode(GenericReplayCharSequence.java:222)
	at org.archive.io.GenericReplayCharSequence.<init>(GenericReplayCharSequence.java:157)
	at org.archive.util.Recorder.getContentReplayCharSequence(Recorder.java:401)
	at org.archive.util.Recorder.getContentReplayCharSequence(Recorder.java:386)
	at org.archive.modules.extractor.ExtractorHTML.innerExtract(ExtractorHTML.java:741)
	at org.archive.modules.extractor.ContentExtractor.extract(ContentExtractor.java:37)
	at org.archive.modules.extractor.Extractor.innerProcess(Extractor.java:102)
	at org.archive.modules.Processor.innerProcessResult(Processor.java:175)
	at org.archive.modules.Processor.process(Processor.java:142)
	at org.archive.modules.ProcessorChain.process(ProcessorChain.java:131)
	at org.archive.crawler.framework.ToeThread.run(ToeThread.java:148)
```

**Comment by justinlittman** [comment]
According to this, should be harmless.

**Comment by justinlittman** [comment]
Sorry.  I think this was a red herring due to running out of space.
