### ISSUE TITLE
Error iterating over problematic WARC

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#301]
Found a problematic WARC in sfm-test.  It produces the following error when iterating over it with twitter_rest_warc_iter:
```
Traceback (most recent call last):
  File "tests/test_twitter_rest_warc_iter.py", line 29, in test_problem
    for i, t in enumerate(warc_iter):
  File "/Users/justinlittman/Data/sfm3/sfm-utils/sfmutils/warc_iter.py", line 44, in iter
    for record_count, record in enumerate(f):
  File "/Users/justinlittman/Data/sfm3/sfm-utils/sfmutils/warc.py", line 30, in __iter__
    for record in self._warc_reader:
  File "/Users/justinlittman/Data/sfm3/sfm-twitter-harvester/ENV/lib/python2.7/site-packages/warc/warc.py", line 393, in __iter__
    record = self.read_record()
  File "/Users/justinlittman/Data/sfm3/sfm-twitter-harvester/ENV/lib/python2.7/site-packages/warc/warc.py", line 364, in read_record
    self.finish_reading_current_record()
  File "/Users/justinlittman/Data/sfm3/sfm-twitter-harvester/ENV/lib/python2.7/site-packages/warc/warc.py", line 359, in finish_reading_current_record
    self.expect(self.current_payload.fileobj, "\r\n")
  File "/Users/justinlittman/Data/sfm3/sfm-twitter-harvester/ENV/lib/python2.7/site-packages/warc/warc.py", line 352, in expect
    raise IOError(message)
IOError: Expected '\r\n', found '3\r\n'
```

I can replicate the problem. However, due to the size of the WARC I cannot add to unit test.

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-utils/commit/653f7f6ee9ac66c1f8d281352a71361914178183

Verified fix by running with problematic WARC and running unit tests.
