### ISSUE TITLE
Heritrix failing at the end of long crawls

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#321]
Not always, but fairly consistently getting something like:

```
2016-06-12 18:41:47.369 INFO thread-30 org.archive.crawler.framework.CrawlController.noteFrontierState() Crawl running.
2016-06-12 18:41:51.107 WARNING thread-50 com.google.common.cache.LocalCache.processPendingNotifications() Exception thrown by removal listener
java.util.ConcurrentModificationException
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1115)
	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1151)
	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1146)
	at com.esotericsoftware.kryo.serialize.MapSerializer.writeObjectData(MapSerializer.java:90)
	at com.esotericsoftware.kryo.serialize.FieldSerializer.writeObjectData(FieldSerializer.java:161)
	at com.esotericsoftware.kryo.Kryo.writeObjectData(Kryo.java:453)
	at com.esotericsoftware.kryo.ObjectBuffer.writeObjectData(ObjectBuffer.java:262)
	at org.archive.bdb.KryoBinding.objectToEntry(KryoBinding.java:81)
	at com.sleepycat.collections.DataView.useValue(DataView.java:549)
	at com.sleepycat.collections.DataCursor.initForPut(DataCursor.java:817)
	at com.sleepycat.collections.DataCursor.put(DataCursor.java:751)
	at com.sleepycat.collections.StoredContainer.putKeyValue(StoredContainer.java:321)
	at com.sleepycat.collections.StoredMap.put(StoredMap.java:279)
	at org.archive.util.ObjectIdentityBdbManualCache$1.onRemoval(ObjectIdentityBdbManualCache.java:122)
	at com.google.common.cache.LocalCache.processPendingNotifications(LocalCache.java:1954)
	at com.google.common.cache.LocalCache$Segment.runUnlockedCleanup(LocalCache.java:3457)
	at com.google.common.cache.LocalCache$Segment.postWriteCleanup(LocalCache.java:3433)
	at com.google.common.cache.LocalCache$Segment.put(LocalCache.java:2888)
	at com.google.common.cache.LocalCache.put(LocalCache.java:4146)
	at org.archive.util.ObjectIdentityBdbManualCache.dirtyKey(ObjectIdentityBdbManualCache.java:379)
	at org.archive.modules.net.CrawlServer.makeDirty(CrawlServer.java:346)
	at org.archive.crawler.frontier.AbstractFrontier.tally(AbstractFrontier.java:623)
	at org.archive.crawler.frontier.AbstractFrontier.doJournalReenqueued(AbstractFrontier.java:662)
	at org.archive.crawler.frontier.WorkQueueFrontier.processFinish(WorkQueueFrontier.java:942)
	at org.archive.crawler.frontier.AbstractFrontier.finished(AbstractFrontier.java:574)
	at org.archive.crawler.framework.ToeThread.run(ToeThread.java:187)
UNREGISTERED FOR KRYO class java.util.LinkedHashSet in class 
```

**Comment by kerchner** [comment]
Also see what state this leaves the WARC file in.

**Comment by justinlittman** [comment]
Not sure if this is the problem, but the current Heritrix configuration has really long delays between retries and performs a large number of retries.  This means that the tail end of a crawl can be stuck on retries for hours.

https://github.com/gwu-libraries/sfm-web-harvester/commit/75ae8d3035c4399ce42345550739fe2971fb4008 dials this back to some more reasonable values.

**Comment by kerchner** [comment]
@justinlittman to test with changes referenced in the previous comment.  If it tests okay, close the ticket for now.

**Comment by justinlittman** [comment]
I believe this is working.  Note that harvests may still take a long time to complete due to lengthy timeouts in the FetchHTTP component.  However, I can't find evidence that anyone else ever tweaks those values, so leaving as is.
