### ISSUE TITLE
Unicode decode error rendering collection page

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#390]
http://gwsfm-prod2.wrlc.org/ui/collections/16/ produces:

```
Thu Jul 28 08:17:57.929910 2016] [:error] [pid 42:tid 140238264743680] Traceback (most recent call last):
[Thu Jul 28 08:17:57.929912 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 164, in get_response
[Thu Jul 28 08:17:57.929915 2016] [:error] [pid 42:tid 140238264743680]     response = response.render()
[Thu Jul 28 08:17:57.929917 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 158, in render
[Thu Jul 28 08:17:57.929920 2016] [:error] [pid 42:tid 140238264743680]     self.content = self.rendered_content
[Thu Jul 28 08:17:57.929922 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 135, in rendered_content
[Thu Jul 28 08:17:57.929926 2016] [:error] [pid 42:tid 140238264743680]     content = template.render(context, self._request)
[Thu Jul 28 08:17:57.929929 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 74, in render
[Thu Jul 28 08:17:57.929932 2016] [:error] [pid 42:tid 140238264743680]     return self.template.render(context)
[Thu Jul 28 08:17:57.929934 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 210, in render
[Thu Jul 28 08:17:57.929937 2016] [:error] [pid 42:tid 140238264743680]     return self._render(context)
[Thu Jul 28 08:17:57.929939 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 202, in _render
[Thu Jul 28 08:17:57.929941 2016] [:error] [pid 42:tid 140238264743680]     return self.nodelist.render(context)
[Thu Jul 28 08:17:57.929944 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
[Thu Jul 28 08:17:57.929946 2016] [:error] [pid 42:tid 140238264743680]     bit = self.render_node(node, context)
[Thu Jul 28 08:17:57.929948 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
[Thu Jul 28 08:17:57.929951 2016] [:error] [pid 42:tid 140238264743680]     return node.render(context)
[Thu Jul 28 08:17:57.929953 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 135, in render
[Thu Jul 28 08:17:57.929956 2016] [:error] [pid 42:tid 140238264743680]     return compiled_parent._render(context)
[Thu Jul 28 08:17:57.929958 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 202, in _render
[Thu Jul 28 08:17:57.929960 2016] [:error] [pid 42:tid 140238264743680]     return self.nodelist.render(context)
[Thu Jul 28 08:17:57.929963 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
[Thu Jul 28 08:17:57.929965 2016] [:error] [pid 42:tid 140238264743680]     bit = self.render_node(node, context)
[Thu Jul 28 08:17:57.929968 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
[Thu Jul 28 08:17:57.929970 2016] [:error] [pid 42:tid 140238264743680]     return node.render(context)
[Thu Jul 28 08:17:57.929972 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
[Thu Jul 28 08:17:57.929975 2016] [:error] [pid 42:tid 140238264743680]     result = block.nodelist.render(context)
[Thu Jul 28 08:17:57.929977 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
[Thu Jul 28 08:17:57.929980 2016] [:error] [pid 42:tid 140238264743680]     bit = self.render_node(node, context)
[Thu Jul 28 08:17:57.929982 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
[Thu Jul 28 08:17:57.929984 2016] [:error] [pid 42:tid 140238264743680]     return node.render(context)
[Thu Jul 28 08:17:57.929987 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 329, in render
[Thu Jul 28 08:17:57.929989 2016] [:error] [pid 42:tid 140238264743680]     return nodelist.render(context)
[Thu Jul 28 08:17:57.929991 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
[Thu Jul 28 08:17:57.929994 2016] [:error] [pid 42:tid 140238264743680]     bit = self.render_node(node, context)
[Thu Jul 28 08:17:57.929997 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
[Thu Jul 28 08:17:57.929999 2016] [:error] [pid 42:tid 140238264743680]     return node.render(context)
[Thu Jul 28 08:17:57.930002 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 224, in render
[Thu Jul 28 08:17:57.930004 2016] [:error] [pid 42:tid 140238264743680]     nodelist.append(node.render(context))
[Thu Jul 28 08:17:57.930007 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 959, in render
[Thu Jul 28 08:17:57.930009 2016] [:error] [pid 42:tid 140238264743680]     output = self.filter_expression.resolve(context)
[Thu Jul 28 08:17:57.930011 2016] [:error] [pid 42:tid 140238264743680]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 675, in resolve
[Thu Jul 28 08:17:57.930014 2016] [:error] [pid 42:tid 140238264743680]     new_obj = func(obj, *arg_vals)
[Thu Jul 28 08:17:57.930017 2016] [:error] [pid 42:tid 140238264743680]   File "/opt/sfm-ui/sfm/ui/templatetags/ui_extras.py", line 34, in json_list
[Thu Jul 28 08:17:57.930019 2016] [:error] [pid 42:tid 140238264743680]     rend = render_dict(j)
[Thu Jul 28 08:17:57.930021 2016] [:error] [pid 42:tid 140238264743680]   File "/opt/sfm-ui/sfm/ui/templatetags/ui_extras.py", line 56, in render_dict
[Thu Jul 28 08:17:57.930024 2016] [:error] [pid 42:tid 140238264743680]     rend += "<li>{}: {}</li>".format(render_key(k), render_value(v))
[Thu Jul 28 08:17:57.930026 2016] [:error] [pid 42:tid 140238264743680] UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-20: ordinal not in range(128)
```

**Comment by Tanych** [comment]
### Unicode Problem
It might be a general problem for current `sfm-ui`. I think we need to find a general way to hand all the related issues.
### Issues related
* **Change history**: `token: "{"track": "#\u6d4b\u8bd5"}" changed to "{"track": "#\u7279\u65af\u8d34\u6211\u997f"}" `
* **UnicodeEncodeError**: `ascii' codec can't encode characters in position 18-20: ordinal not in range(128)`

### Temporary Solution
Make changes on all the related methods. For example, `json.dump` and `format` are frequently called in `sfm-ui` and other harvesters.  The default strings handled by these methods in `python 2`  are [str](https://docs.python.org/2/library/functions.html#str). The related changes are as follows:
* [json.dump](https://docs.python.org/2/library/json.html)(*, `ensure_ascii=False`)
* using `u''` instead of `' ' ` before [format](https://docs.python.org/2/library/stdtypes.html#str.format)

### Import unicode_literals
There are lots of debates on this topic and the official listed the benefits and drawbacks.
http://python-future.org/unicode_literals.html

### Django Suggestion
https://docs.djangoproject.com/en/1.8/ref/unicode/#general-string-handling

**Comment by kerchner** [comment]
@justinlittman suggests changing TextField field types to JSONField types.
