### ISSUE TITLE
Ascii error in web harvester

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#406]
```
2016-08-16 13:21:34,344: sfmutils.harvester --> Unknown error raised during harvest
Traceback (most recent call last):
  File "/opt/sfm-utils/sfmutils/harvester.py", line 169, in on_message
    self.harvest_seeds()
  File "web_harvester.py", line 39, in harvest_seeds
    f.write(url)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 40-46: ordinal not in range(128)
```

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-web-harvester/commit/ef61035f0dd10fe8ae60153ca1129f304def426a
