### ISSUE TITLE
Heritrix error when nothing downloaded

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#440]
```
2016-09-14 10:43:02,141: kombu.mixins --> Connection to broker lost, trying to re-establish connection...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/kombu/mixins.py", line 177, in run
    for _ in self.consume(limit=None):  # pragma: no cover
  File "/usr/local/lib/python2.7/site-packages/kombu/mixins.py", line 199, in consume
    conn.drain_events(timeout=safety_interval)
  File "/usr/local/lib/python2.7/site-packages/librabbitmq/__init__.py", line 220, in drain_events
    self._basic_recv(timeout)
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 598, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 564, in receive
    [callback(body, message) for callback in callbacks]
  File "/usr/local/lib/python2.7/site-packages/sfmutils/consumer.py", line 121, in _callback
    self.on_message()
  File "/usr/local/lib/python2.7/site-packages/sfmutils/harvester.py", line 183, in on_message
    self._process(done=True)
  File "/usr/local/lib/python2.7/site-packages/sfmutils/harvester.py", line 211, in _process
    for warc_filename in self._list_warcs(self.warc_temp_dir):
  File "/usr/local/lib/python2.7/site-packages/sfmutils/harvester.py", line 279, in _list_warcs
    warcs = [f for f in os.listdir(path) if os.path.isfile(os.path.join(path, f)) and
OSError: [Errno 2] No such file or directory: '/sfm-data/heritrix-data/jobs/sfm/latest/warcs'
```

**Comment by justinlittman** [comment]
Problem solved by harvester refactor.
