### ISSUE TITLE
SFM UI consumer crash

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#460]
This occurred on PROD:
```
Traceback (most recent call last):
  File "/opt/sfm-ui/sfm/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/sfm-ui/sfm/message_consumer/management/commands/startconsumer.py", line 20, in handle
    consumer.run()
  File "/usr/local/lib/python2.7/site-packages/kombu/mixins.py", line 177, in run
    for _ in self.consume(limit=None):  # pragma: no cover
  File "/usr/local/lib/python2.7/site-packages/kombu/mixins.py", line 199, in consume
    conn.drain_events(timeout=safety_interval)
  File "/usr/local/lib/python2.7/site-packages/librabbitmq/__init__.py", line 220, in drain_events
    self._basic_recv(timeout)
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 598, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 564, in receive
    [callback(body, message) for callback in callbacks]
  File "/usr/local/lib/python2.7/site-packages/sfmutils/consumer.py", line 121, in _callback
    self.on_message()
  File "/opt/sfm-ui/sfm/message_consumer/sfm_ui_consumer.py", line 28, in on_message
    self._on_harvest_status_message()
  File "/opt/sfm-ui/sfm/message_consumer/sfm_ui_consumer.py", line 71, in _on_harvest_status_message
    seed.save()
  File "/opt/sfm-ui/sfm/ui/models.py", line 302, in save
    return history_save(self, *args, **kw)
  File "/opt/sfm-ui/sfm/ui/models.py", line 48, in history_save
    return super(self.__class__, self).save(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 827, in _save_table
    forced_update)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 877, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 580, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "token" violates not-null constraint
DETAIL:  Failing row contains (587, 317e40dc054041eca9ef791553284d07, null, 773326419573116928, t, t, 2016-09-15 21:55:22.994699+00, 2016-09-22 15:26:31.336947+00, Changed token based on information from harvester from harvest 3..., 55).
```

It resulted in messages not being consumed for several days.

**Comment by justinlittman** [comment]
And another reason that the consumer should be in its own container so that it can be automatically restarted.

**Comment by kerchner** [comment]
Ref #455
