### ISSUE TITLE
Sfm-ui Pending update

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-ui#508]
@justinlittman I have tried this several time for current master branch.
### Process
1. build a twitter user timeline collection
2. waiting for the collection compelted
3. sfm-ui has no updates for the collection when the collection actually completed.
![penging](https://cloud.githubusercontent.com/assets/3956411/19867413/1b814ecc-9f7a-11e6-8c44-cd99afcccb8d.png)

### Expect
It shows updates and completed and stats.

### Error
```python
Traceback (most recent call last):
  File "/opt/sfm-ui/sfm/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/sfm-ui/sfm/message_consumer/management/commands/startconsumer.py", line 20, in handle
    consumer.run()
  File "/usr/local/lib/python2.7/site-packages/kombu/mixins.py", line 170, in run
    for _ in self.consume(limit=None, **kwargs):
  File "/usr/local/lib/python2.7/site-packages/kombu/mixins.py", line 192, in consume
    conn.drain_events(timeout=safety_interval)
  File "/usr/local/lib/python2.7/site-packages/librabbitmq/__init__.py", line 220, in drain_events
    self._basic_recv(timeout)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/librabbitmq.py", line 45, in __init__
    headers=props.get('headers'))
TypeError: __init__() got multiple values for keyword argument 'body'

```

**Comment by justinlittman** [comment]
Fixed by:
* https://github.com/gwu-libraries/sfm-utils/commit/3e9cfcc9bf28a8ae44a6619212fae73a44fdc953
* https://github.com/gwu-libraries/sfm-ui/commit/4f0634523efc5644222e219db1786460092d363b
* https://github.com/gwu-libraries/sfm-web-harvester/commit/fe66f1361eac28fbe169ced36fb7b829992f8326

**Comment by justinlittman** [comment]
To get the fix, `docker-compose pull`.
