### ISSUE TITLE
Errors when upgrading to 1.3.0

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#528]
From test instance:
```
  Applying ui.0005_user_harvest_notifications... OK
Traceback (most recent call last):
  File "/opt/sfm-ui/sfm/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 62, in database_forwards
    field,
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 398, in add_field
    self.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: could not create unique index "ui_credential_credential_id_key"
DETAIL:  Key (credential_id)=(bb2372bf073849bcbe36f3bad64504a4) is duplicated.

  Applying ui.0006_auto_20161101_1121...Migrating db
Operations to perform:
  Synchronize unmigrated apps: weibo, simple_history, apscheduler, staticfiles, datetimewidget, twitter, api, messages, tumblr, allauth, humanize, finalware, rest_framework, message_consumer, crispy_forms
  Apply all migrations: account, sessions, admin, sites, auth, contenttypes, ui, socialaccount
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
Traceback (most recent call last):
  File "/opt/sfm-ui/sfm/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 62, in database_forwards
    field,
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 398, in add_field
    self.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: could not create unique index "ui_credential_credential_id_key"
DETAIL:  Key (credential_id)=(2261c9044f1348809b50dc375e6fe454) is duplicated.
```

and then 500 from error when viewing collection detail page:
```
[Mon Nov 14 15:32:35.389570 2016] [wsgi:error] [pid 51:tid 140158854883072] ERROR 2016-11-14 15:32:35,386 51 django.request Internal Server Error: /ui/collections/5/
[Mon Nov 14 15:32:35.389585 2016] [wsgi:error] [pid 51:tid 140158854883072] Traceback (most recent call last):
[Mon Nov 14 15:32:35.389589 2016] [wsgi:error] [pid 51:tid 140158854883072]   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
[Mon Nov 14 15:32:35.389592 2016] [wsgi:error] [pid 51:tid 140158854883072]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Mon Nov 14 15:32:35.389595 2016] [wsgi:error] [pid 51:tid 140158854883072]   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
[Mon Nov 14 15:32:35.389598 2016] [wsgi:error] [pid 51:tid 140158854883072]     return self.dispatch(request, *args, **kwargs)
[Mon Nov 14 15:32:35.389600 2016] [wsgi:error] [pid 51:tid 140158854883072]   File "/usr/local/lib/python2.7/site-packages/braces/views/_access.py", line 98, in dispatch
[Mon Nov 14 15:32:35.389610 2016] [wsgi:error] [pid 51:tid 140158854883072]     request, *args, **kwargs)
[Mon Nov 14 15:32:35.389613 2016] [wsgi:error] [pid 51:tid 140158854883072]   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
[Mon Nov 14 15:32:35.389616 2016] [wsgi:error] [pid 51:tid 140158854883072]     return handler(request, *args, **kwargs)
[Mon Nov 14 15:32:35.389619 2016] [wsgi:error] [pid 51:tid 140158854883072]   File "/usr/local/lib/python2.7/site-packages/django/views/generic/detail.py", line 116, in get
[Mon Nov 14 15:32:35.389622 2016] [wsgi:error] [pid 51:tid 140158854883072]     context = self.get_context_data(object=self.object)
[Mon Nov 14 15:32:35.389631 2016] [wsgi:error] [pid 51:tid 140158854883072]   File "/opt/sfm-ui/sfm/ui/views.py", line 116, in get_context_data
[Mon Nov 14 15:32:35.389634 2016] [wsgi:error] [pid 51:tid 140158854883072]     context["last_harvest"] = self.object.last_harvest()
[Mon Nov 14 15:32:35.389637 2016] [wsgi:error] [pid 51:tid 140158854883072]   File "/opt/sfm-ui/sfm/ui/models.py", line 355, in last_harvest
[Mon Nov 14 15:32:35.389640 2016] [wsgi:error] [pid 51:tid 140158854883072]     return self.harvests.exclude(harvest_type="web").order_by("-date_requested").first()
[Mon Nov 14 15:32:35.389648 2016] [wsgi:error] [pid 51:tid 140158854883072]   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 490, in first
[Mon Nov 14 15:32:35.389652 2016] [wsgi:error] [pid 51:tid 140158854883072]     objects = list((self if self.ordered else self.order_by('pk'))[:1])
[Mon Nov 14 15:32:35.389654 2016] [wsgi:error] [pid 51:tid 140158854883072]   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 162, in __iter__
[Mon Nov 14 15:32:35.389657 2016] [wsgi:error] [pid 51:tid 140158854883072]     self._fetch_all()
[Mon Nov 14 15:32:35.389660 2016] [wsgi:error] [pid 51:tid 140158854883072]   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
[Mon Nov 14 15:32:35.389668 2016] [wsgi:error] [pid 51:tid 140158854883072]     self._result_cache = list(self.iterator())
[Mon Nov 14 15:32:35.389671 2016] [wsgi:error] [pid 51:tid 140158854883072]   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
[Mon Nov 14 15:32:35.389675 2016] [wsgi:error] [pid 51:tid 140158854883072]     results = compiler.execute_sql()
[Mon Nov 14 15:32:35.389677 2016] [wsgi:error] [pid 51:tid 140158854883072]   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
[Mon Nov 14 15:32:35.389687 2016] [wsgi:error] [pid 51:tid 140158854883072]     cursor.execute(sql, params)
[Mon Nov 14 15:32:35.389690 2016] [wsgi:error] [pid 51:tid 140158854883072]   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
[Mon Nov 14 15:32:35.389693 2016] [wsgi:error] [pid 51:tid 140158854883072]     return self.cursor.execute(sql, params)
[Mon Nov 14 15:32:35.389695 2016] [wsgi:error] [pid 51:tid 140158854883072]   File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
[Mon Nov 14 15:32:35.389698 2016] [wsgi:error] [pid 51:tid 140158854883072]     six.reraise(dj_exc_type, dj_exc_value, traceback)
[Mon Nov 14 15:32:35.389701 2016] [wsgi:error] [pid 51:tid 140158854883072]   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
[Mon Nov 14 15:32:35.389710 2016] [wsgi:error] [pid 51:tid 140158854883072]     return self.cursor.execute(sql, params)
[Mon Nov 14 15:32:35.389713 2016] [wsgi:error] [pid 51:tid 140158854883072] ProgrammingError: column ui_harvest.service does not exist
[Mon Nov 14 15:32:35.389715 2016] [wsgi:error] [pid 51:tid 140158854883072] LINE 1: ...rvest"."warcs_count", "ui_harvest"."warcs_bytes", "ui_harves...
```

**Comment by justinlittman** [comment]
And herein lies the problem:  https://code.djangoproject.com/ticket/23932

The new credential id field is not getting set with a unique UUID.

**Comment by justinlittman** [comment]
And here is the solution: https://docs.djangoproject.com/en/1.8/howto/writing-migrations/#migrations-that-add-unique-fields
