### ISSUE TITLE
Deserialization error

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#539]
Steps to reproduce:
1.  Serialize the Election collection set on production.
2.  Copy the collection set to a new instance of SFM running 1.3.
3. Deserialize the collection set.

Expected result:
Deserialization completes successfully

Actual result:
```
root@93355dc87c70:/opt/sfm-ui/sfm# ./manage.py deserializecollectionset /sfm-data/collection_set/a5120a757d094ebcaffe17cdefa7985e 
Deserializing
INFO 2016-11-16 16:01:29,284 161 ui.serialize Deserializing collection set at /sfm-data/collection_set/a5120a757d094ebcaffe17cdefa7985e
INFO 2016-11-16 16:01:29,284 161 ui.serialize Deserializing collection at /sfm-data/collection_set/a5120a757d094ebcaffe17cdefa7985e/07d7c495ca0242fda2664bd882828ddb
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/sfm-ui/sfm/ui/management/commands/deserializecollectionset.py", line 20, in handle
    serializer.deserialize_collection_set(options["collection_set_path"])
  File "/opt/sfm-ui/sfm/ui/serialize.py", line 326, in deserialize_collection_set
    self.deserialize_collection(collection_path)
  File "/opt/sfm-ui/sfm/ui/serialize.py", line 432, in deserialize_collection
    self._deserialize(harvest_filepath)
  File "/opt/sfm-ui/sfm/ui/serialize.py", line 501, in _deserialize
    for d_obj in self._deserialize_iter(filepath):
  File "/opt/sfm-ui/sfm/ui/serialize.py", line 508, in _deserialize_iter
    for d_obj in serializers.deserialize("json", f):
  File "/usr/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 85, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 79, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/usr/local/lib/python2.7/site-packages/django/core/serializers/python.py", line 139, in Deserializer
    obj = field.rel.to._default_manager.db_manager(db).get_by_natural_key(*field_value)
  File "/opt/sfm-ui/sfm/ui/models.py", line 80, in get_by_natural_key
    return self.get(credential_id=credential_id, history_date=history_date)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
django.core.serializers.base.DeserializationError: HistoricalCredential matching query does not exist.
```

**Comment by justinlittman** [comment]
Here's what I think is happening:  When migrating from 1.2 to 1.3 a credential_id field was added to credential and historical credential.  I don't believe that the credential_id was set on the historical credential to match the credential.

To reproduce, bring up SFM 1.2, create a credential, and the upgrade to SFM 1.3.
