### ISSUE TITLE
Error on restart from file

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#575]
Found on sfm-sandbox:

```
2016-12-03 23:47:50,894: sfmutils.harvester --> Starting WARC processing thread
2016-12-03 23:47:50,894: sfmutils.consumer --> /sfm-data/containers/832d100e0439/last_message.json exists, so resuming
2016-12-03 23:47:50,894: sfmutils.consumer --> Loading from file /sfm-data/containers/832d100e0439/last_message.json
2016-12-03 23:47:50,894: sfmutils.harvester --> Harvesting by message with id 82c69c3089fc4d2bbc316e5194afeff7
Traceback (most recent call last):
  File "twitter_harvester.py", line 246, in <module>
    TwitterHarvester.main(TwitterHarvester, QUEUE, [SEARCH_ROUTING_KEY, TIMELINE_ROUTING_KEY])
  File "/usr/local/lib/python2.7/site-packages/sfmutils/harvester.py", line 606, in main
    harvester.resume_from_file()
  File "/usr/local/lib/python2.7/site-packages/sfmutils/consumer.py", line 192, in resume_from_file
    self.message_from_file(self.message_filepath, delete=True)
  File "/usr/local/lib/python2.7/site-packages/sfmutils/consumer.py", line 177, in message_from_file
    self.on_message()
  File "/usr/local/lib/python2.7/site-packages/sfmutils/harvester.py", line 165, in on_message
    self._send_status_message(STATUS_RUNNING)
  File "/usr/local/lib/python2.7/site-packages/sfmutils/harvester.py", line 377, in _send_status_message
    "date_started": self.result.started.isoformat(),
AttributeError: 'NoneType' object has no attribute 'isoformat'
```

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-utils/commit/8a333cdcf16aa8420eb192b52753d5e031479f44
