### ISSUE TITLE
Twitter filter needs a tweet to stop

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#579]
Steps to reproduce:
1.  Start a Twitter filter collection, filtering on something that doesn't actually collect any tweets.
2. Turn off the collection.
3.  Wait

Expected result:
Harvest ends and returns a result.

Actual result:
Harvest does not end and return a result.

This is because the harvester only checks if it should end after a tweet is returned. It does not interrupt blocking waiting for Twarc.  A timeout will need to be added to Twarc.

**Comment by lwrubel** [comment]
First assess approach and reassign LoE if needed.

**Comment by justinlittman** [comment]
Suggested implementation:  Allow passing an optional threading.Event to twarc methods.  This event will be checked during iteration.  Twitter sends newlines ("keep-alives") every 30 seconds, so this should be the maximum time before iteration is interrupted.

**Comment by justinlittman** [comment]
Branches for this ticket:
* https://github.com/gwu-libraries/sfm-ui/tree/t579-stop
* https://github.com/gwu-libraries/sfm-utils/compare/sfm_579-stop
* https://github.com/gwu-libraries/sfm-twitter-harvester/tree/t579-stop_twitter

Testing this will require building the Twitter stream harvester.

**Comment by justinlittman** [comment]
TODO:  Add documentation info on using `docker-compose -t 180`.  This is because stopping the stream harvester gracefully may take some time.

**Comment by lwrubel** [comment]
@Tanych: start taking a look at this one, PR to be created shortly.

**Comment by justinlittman** [comment]
Pull requests are:
* https://github.com/gwu-libraries/sfm-ui/pull/654
* https://github.com/gwu-libraries/sfm-utils/pull/28
* https://github.com/gwu-libraries/sfm-twitter-harvester/pull/32
And requires the latest master for warcprox.

**Comment by Tanych** [comment]
@justinlittman 
Tests for the stream twitter stop or pause.
## Test Case 1
* corner case: seed with no tweets
* collection type : twitter filter
* seed: `track: gwu libraries` 

### Steps
* building `twitter-stream` container locally
* building a `twitter filter` collection with seed `track:gwu libraries`
* turn on the collection
* waiting for 2-3 minutes
* turn off the collection 

### Results
no tweets return, status marked as `stop request` in sfm-ui but exception in errors log.
```
2017-01-30 10:12:16,741: sfmutils.harvester --> Done harvesting by message with id 3d5ec47a121e4185a6f294ae5a1aae9e
2017-01-30 10:12:16,741: sfmutils.warcprox --> Shutting down warcprox
2017-01-30 10:12:16,741: sfmutils.warcprox --> Waiting for warcprox to terminate
2017-01-30 10:12:16,741: sfmutils.warcprox --> Killing warcprox
Exception in thread warc_processing_thread (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
  File "/opt/sfm-utils/sfmutils/harvester.py", line 501, in _process_warc_thread
  File "/usr/local/lib/python2.7/Queue.py", line 172, in get
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```
### Resume
resume the collection and collection has been skipped.

## Test Case 2
* collection type : twitter filter
* seed: `track: trump` 

### Steps
* building `twitter-stream` container locally
* building a `twitter filter` collection with seed `track:trump`
* turn on the collection
* waiting for 2-3 minutes
* turn off the collection 

### Results
5984 tweets return, status marked as `success` but exception in errors log.
```
2017-01-30 10:12:16,741: sfmutils.harvester --> Done harvesting by message with id 3d5ec47a121e4185a6f294ae5a1aae9e
2017-01-30 10:12:16,741: sfmutils.warcprox --> Shutting down warcprox
2017-01-30 10:12:16,741: sfmutils.warcprox --> Waiting for warcprox to terminate
2017-01-30 10:12:16,741: sfmutils.warcprox --> Killing warcprox
Exception in thread warc_processing_thread (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
  File "/opt/sfm-utils/sfmutils/harvester.py", line 501, in _process_warc_thread
  File "/usr/local/lib/python2.7/Queue.py", line 172, in get
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```
### Resume
resume the collection and then turn off the collection in 2 minutes.
* tweets return but same error,

**Comment by justinlittman** [comment]
I don't believe this error is problematic:

```
Exception in thread warc_processing_thread (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
  File "/opt/sfm-utils/sfmutils/harvester.py", line 501, in _process_warc_thread
  File "/usr/local/lib/python2.7/Queue.py", line 172, in get
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

It has to do with threads shutting down.

**Comment by justinlittman** [comment]
@Tanych I can't reproduce the problem with test case 1.  Let's take a look together when you're in.

**Comment by Tanych** [comment]
@justinlittman  I have re-test the test case 1, it has no such problem.  I will confirm it again.

**Comment by Tanych** [comment]
I didn't wait the response from the first harvest and turn it on immediately, so it's skipped.  It's the problem #625.

**Comment by justinlittman** [comment]
Merged.
