### ISSUE TITLE
ELK elasticsearch indexing

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#598]
The current scripts whereby tweets are loaded with logstash result in a long list of indices (of the form `logstash-<date>`.   Elasticsearch seems to get hung up when loaded with >100K tweets.  It seems to me that we should be creating one index (could be wrong here).

This may be what's crashing Elasticsearch, which is preventing realistic use of the ELK container.  It is a high-priority request from Program on Extremism to have the ELK container work for their data set, which currently consists of roughly 900,000 tweets.

**Comment by Tanych** [comment]
### Loading 200k tweets
The node seems to work normal and all the shards and replica work well. The default shards number is 5 and 1 replica. For a single node, there are 10 shards in total.

* Overview

![overview](https://cloud.githubusercontent.com/assets/3956411/21782600/f2898130-d681-11e6-8c65-4ee99879d54b.png)

* Search 
![search](https://cloud.githubusercontent.com/assets/3956411/21782748/8ebb8d78-d682-11e6-9a06-847a6b706cba.png)


I think single indexing or multi-indexing is not the problem, as the [official doc](https://www.elastic.co/guide/en/elasticsearch/guide/current/multiple-indices.html#multiple-indices) says:

>Searching 1 index of 50 shards is exactly equivalent to searching 50 indices with 1 shard each: both search requests hit 50 shards.

I am not sure whether there are problem when dataset reaches 1,000,000 level. Need to find out the exact reason to crush the elasticsearch. It might be disk space or other issues.

**Comment by Tanych** [comment]
Main issue detected:
```
[2017-01-09 19:53:54,486][DEBUG][action.search            ] [Centurious] [342] Failed to execute fetch phase
RemoteTransportException[[Centurious][172.18.0.10:9300][indices:data/read/search[phase/fetch/id]]]; nested: IllegalArgumentException[field [kibanaSavedObjectMeta] isn't a leaf field];
Caused by: java.lang.IllegalArgumentException: field [kibanaSavedObjectMeta] isn't a leaf field
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:139)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:605)
        at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:408)
        at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:405)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2017-01-09 19:53:54,486][DEBUG][action.search            ] [Centurious] [343] Failed to execute fetch phase
RemoteTransportException[[Centurious][172.18.0.10:9300][indices:data/read/search[phase/fetch/id]]]; nested: IllegalArgumentException[field [geoip] isn't a leaf field];
Caused by: java.lang.IllegalArgumentException: field [geoip] isn't a leaf field
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:139)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:605)
        at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:408)
        at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:405)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2017-01-09 20:43:21,323][DEBUG][action.search            ] [Centurious] [1572] Failed to execute fetch phase
RemoteTransportException[[Centurious][172.18.0.10:9300][indices:data/read/search[phase/fetch/id]]]; nested: IllegalArgumentException[field [geoip] isn't a leaf field];
Caused by: java.lang.IllegalArgumentException: field [geoip] isn't a leaf field
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:139)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:605)
        at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:408)
        at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:405)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

```
Lots of smiliar error.

Need to figure out what's wrong with elasticasearch.

**Comment by kerchner** [comment]
@Tanych Good work tracking this down.  I'll be interested to see what the root cause is.

**Comment by Tanych** [comment]
@kerchner 
I remove the volume of the `sfm_elk` and restart the container. It loads successfully when processing 2,284,247 tweets.

**Comment by Tanych** [comment]
issue related log
```
Waiting for elk
 * Starting periodic command scheduler cron
   ...done.
 * Starting Elasticsearch Server
sysctl: setting key "vm.max_map_count": Read-only file system
   ...fail!
waiting for Elasticsearch to be up (1/30)
waiting for Elasticsearch to be up (2/30)
waiting for Elasticsearch to be up (3/30)
waiting for Elasticsearch to be up (4/30)
waiting for Elasticsearch to be up (5/30)
waiting for Elasticsearch to be up (6/30)
waiting for Elasticsearch to be up (7/30)
waiting for Elasticsearch to be up (8/30)
waiting for Elasticsearch to be up (9/30)
waiting for Elasticsearch to be up (10/30)
waiting for Elasticsearch to be up (11/30)
waiting for Elasticsearch to be up (12/30)
waiting for Elasticsearch to be up (13/30)
waiting for Elasticsearch to be up (14/30)
waiting for Elasticsearch to be up (15/30)
waiting for Elasticsearch to be up (16/30)
waiting for Elasticsearch to be up (17/30)
waiting for Elasticsearch to be up (18/30)
waiting for Elasticsearch to be up (19/30)
waiting for Elasticsearch to be up (20/30)
waiting for Elasticsearch to be up (21/30)
waiting for Elasticsearch to be up (22/30)
waiting for Elasticsearch to be up (23/30)
waiting for Elasticsearch to be up (24/30)
waiting for Elasticsearch to be up (25/30)
waiting for Elasticsearch to be up (26/30)
waiting for Elasticsearch to be up (27/30)
waiting for Elasticsearch to be up (28/30)
waiting for Elasticsearch to be up (29/30)
waiting for Elasticsearch to be up (30/30)
Couln't start Elasticsearch. Exiting.
Elasticsearch log follows below.

```

https://github.com/spujadas/elk-docker/issues/99

**Comment by Tanych** [comment]
The main issue is that the elastic-search can't start once it has exited no matter what you have done before.

**Comment by lwrubel** [comment]
@justinlittman: please consider and suggest which path to pursue.

**Comment by justinlittman** [comment]
As a workaround, remove the container (`docker-compose rm -vf elk`) after stopping it.

**Comment by justinlittman** [comment]
PR for this ticket:  https://github.com/gwu-libraries/sfm-elk/pull/8

See also https://github.com/gwu-libraries/sfm-docker/commit/2f07b11a372a98a924bfb6737d61e5720f152b4c

**Comment by kerchner** [comment]
@justinlittman Wouldn't removing the container (as per above) blow away the result of elasticsearch indexing the data?

**Comment by justinlittman** [comment]
Nope.  ES indexes are stored outside of the container.

**Comment by Tanych** [comment]
@kerchner @justinlittman 
## Test case 1
Restart container: Kill the container and then restart the container to check whether the elastic-search can start normally.
### Results
* [x] It works well. No fails in setting the  vm.max_map_count. 

## Test case 2
Loading large set tweets into elastcisearch
### Steps
* building sfm-elk container locally.
* building a tweet filter `trump`.
* running collection more than 16 hours.
* check the status of the elk.

### Results
Loading tweets: `2,805,616`. sfm-elk won't load the duplicate tweets. The sfm-elk status seems fine:
* Tweet dashboard

![tweets_status](https://cloud.githubusercontent.com/assets/3956411/22470610/dc270304-e79d-11e6-90f8-b4d697d3a959.png)

* Node status

![status](https://cloud.githubusercontent.com/assets/3956411/22469917/914368fc-e79b-11e6-92d8-7c9d7cc447be.png)
 > status from Elastic-HQ

* [x] No error in logs and tweets visualization seems fine.

## Suggestion
Install some elasticsearch plugin on sfm-elk to do monitoring or node diagnostics. Plugins can be  [Elastic-HQ](http://www.elastichq.org/), [Paramedic](https://github.com/karmi/elasticsearch-paramedic), or [Bigdeskhttp](https://github.com/lukas-vlcek/bigdesk/).

It's good to go.

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-elk/commit/acbcf3ea5184cb60af1146db611f08bbd3d08af8

**Comment by kerchner** [comment]
@Tanych @justinlittman  Thanks for your thorough testing and work on this.
