### ISSUE TITLE
'urls.py' and 'unshorten.py' generate errors

### ISSUE THREAD

**Issue by soominpark** [gwu-libraries/sfm-ui#652]
When I ran 'urls.py', trying to extract URLs from a WARC file, as written in the “Extracting URLs from #PulseNightclub for seeding web archiving” blog post, an error occured and it didn't work.
The reason of the error seems to be that there are some blanks in the URL field. 'unshorten.py' did not work as well. Please check them out. 

#### Command that I ran
```
twitter_stream_warc_iter.py /sfm-data/collection_set/d685951a9846411b9dd2b70fab1e32b3/b0953d57a98842f08d4eb58dcd79940f/2017/01/19/17/a3bbef3c35eb497594ddb9a208837b17-20170119170517671-00000-58-e19dce0f6248-8000.warc.gz | python /opt/twarc/utils/urls.py

```

#### Result
```python
Traceback (most recent call last):
  File "/opt/twarc/utils/urls.py", line 17, in <module>
    print(url['expanded_url'].encode('utf8'))
AttributeError: 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
  File "/usr/local/bin/twitter_stream_warc_iter.py", line 38, in <module>
    TwitterStreamWarcIter.main(TwitterStreamWarcIter)
  File "/usr/local/lib/python2.7/dist-packages/sfmutils/warc_iter.py", line 214, in main
    print_item_type=args.print_item_type, dedupe=args.dedupe)
  File "/usr/local/lib/python2.7/dist-packages/sfmutils/warc_iter.py", line 131, in print_iter
    json.dump(item, fp, indent=4 if pretty else None)
  File "/usr/lib/python2.7/json/__init__.py", line 190, in dump
    fp.write(chunk)
IOError: [Errno 32] Broken pipe

```

**Comment by justinlittman** [comment]
Fix is in https://github.com/DocNow/twarc/pull/141

**Comment by lwrubel** [comment]
Depends on new twarc release; upgrade when available.

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-twitter-harvester/commit/57c00e8c4356551cf4da7a07bbde73359471e7d7
