### ISSUE TITLE
None seeds cause problem for web harvester

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#656]
It appears that the Twitter Rest Harvester may be sending seeds with value of None to the web harvester, that is causing problems for the web harvester.

From the [U.S. House Representatives (115th Congress) Official Twitter User Timelines](http://gwsfm-prod2.wrlc.org/ui/collections/96/):

```
bharvester_1            | 2017-01-27 19:55:41,134: __main__ --> http://www.leahy.senate.gov/press/statement-of-senator-patrick-leahy-d-vt-chairman-senate-committee-on-the-judiciary_on-senate-considerat
ion-of-the-runaway-and-homeless-youth-and-trafficking-prevention-act
webharvester_1            | 2017-01-27 19:55:41,134: __main__ --> http://bit.ly/UmlTmV
webharvester_1            | 2017-01-27 19:55:41,134: __main__ --> http://www.nytimes.com/2016/08/16/well/swimming-simone-manuel-black-children.html
webharvester_1            | 2017-01-27 19:55:41,134: __main__ --> None
webharvester_1            | 2017-01-27 19:55:41,137: sfmutils.harvester --> Unknown error raised during harvest: coercing to Unicode: need string or buffer, NoneType found
webharvester_1            | Traceback (most recent call last):
webharvester_1            |   File "/usr/local/lib/python2.7/site-packages/sfmutils/harvester.py", line 228, in on_message
webharvester_1            |     self.harvest_seeds()
webharvester_1            |   File "web_harvester.py", line 54, in harvest_seeds
webharvester_1            |     f.write(url)
webharvester_1            |   File "/usr/local/lib/python2.7/codecs.py", line 706, in write
webharvester_1            |     return self.writer.write(data)
webharvester_1            |   File "/usr/local/lib/python2.7/codecs.py", line 369, in write
webharvester_1            |     data, consumed = self.encode(object, self.errors)
webharvester_1            | TypeError: coercing to Unicode: need string or buffer, NoneType found
webharvester_1            | 2017-01-27 19:55:41,138: sfmutils.harvester --> Too many retries, so giving up on harvesting seeds.
```

**Comment by justinlittman** [comment]
Fixed by:
* https://github.com/gwu-libraries/sfm-web-harvester/commit/5305d29ec781bfbab4e795cfe4e564a43f1c61bf
* https://github.com/gwu-libraries/sfm-utils/commit/24de866e8c1d84e93c4ca6414b74562f500910bc
