### ISSUE TITLE
Unhandled stream exception

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#728]
I've seen this multiple times on production.  Collecting stops without notification.

```
2017-03-01 11:52:11,114: sfmutils.warcprox --> Shutting down warcprox
2017-03-01 11:52:14,119: sfmutils.warcprox --> Executing warcprox -c /tmp/tmp6NvIII/warcprox-ca.pem --certs-dir /tmp/tmp6NvIII --dedup-db-file /dev/null -d /sfm-data/containers/8efed98eb514/tmp/fbedf1084ddf4b1a86ecd25810622b8a -n fbedf1084ddf4b1a86ecd25810622b8a -p 8000 -z -i
2017-03-01 11:52:14,165: sfmutils.harvester --> Processing fbedf1084ddf4b1a86ecd25810622b8a-20170301163656828-00000-20174-8efed98eb514-8000.warc.gz
2017-03-01 11:52:14,165: sfmutils.warc_iter --> Iterating over /sfm-data/containers/8efed98eb514/tmp/fbedf1084ddf4b1a86ecd25810622b8a/fbedf1084ddf4b1a86ecd25810622b8a-20170301163656828-00000-20174-8efed98eb514-8000.warc.gz
2017-03-01 11:52:19,126: root --> creating http session
2017-03-01 11:52:19,127: root --> connecting to filter stream for {'track': u'#MakeAmericaGreatAgain, #MAGA, Make America Great Again', 'stall_warning': True}
2017-03-01 11:52:19,129: requests.packages.urllib3.connectionpool --> Starting new HTTPS connection (1): stream.twitter.com
2017-03-01 12:00:05,926: root --> keep-alive
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/site-packages/warcprox/warcprox.py", line 158, in __init__
    warcprox.mitmproxy.MitmProxyHandler.__init__(self, request, client_address, server)
  File "/usr/local/lib/python2.7/site-packages/warcprox/mitmproxy.py", line 25, in __init__
    http_server.BaseHTTPRequestHandler.__init__(self, request, client_address, server)
  File "/usr/local/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/lib/python2.7/site-packages/warcprox/mitmproxy.py", line 96, in do_CONNECT
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/lib/python2.7/site-packages/warcprox/mitmproxy.py", line 131, in do_COMMAND
    self._proxy_request()
  File "/usr/local/lib/python2.7/site-packages/warcprox/warcprox.py", line 218, in _proxy_request
    raise e
IncompleteRead: IncompleteRead(3474 bytes read)
2017-03-01 12:00:38,292: root --> caught exception ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)) on 1 try
2017-03-01 12:00:38,292: root --> ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
2017-03-01 12:00:38,292: root --> sleeping 1
2017-03-01 12:00:39,294: root --> connecting to filter stream for {'track': u'#MakeAmericaGreatAgain, #MAGA, Make America Great Again', 'stall_warning': True}
2017-03-01 12:00:39,295: requests.packages.urllib3.connectionpool --> Resetting dropped connection: stream.twitter.com
2017-03-01 12:00:39,295: requests.packages.urllib3.connectionpool --> Starting new HTTPS connection (2): stream.twitter.com
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/site-packages/warcprox/warcprox.py", line 158, in __init__
    warcprox.mitmproxy.MitmProxyHandler.__init__(self, request, client_address, server)
  File "/usr/local/lib/python2.7/site-packages/warcprox/mitmproxy.py", line 25, in __init__
    http_server.BaseHTTPRequestHandler.__init__(self, request, client_address, server)
  File "/usr/local/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/lib/python2.7/site-packages/warcprox/mitmproxy.py", line 96, in do_CONNECT
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/lib/python2.7/site-packages/warcprox/mitmproxy.py", line 131, in do_COMMAND
    self._proxy_request()
  File "/usr/local/lib/python2.7/site-packages/warcprox/warcprox.py", line 218, in _proxy_request
    raise e
IncompleteRead: IncompleteRead(1978 bytes read)
2017-03-01 12:00:40,441: root --> caught exception ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)) on 1 try
2017-03-01 12:00:40,441: root --> ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
2017-03-01 12:00:40,441: root --> sleeping 1
2017-03-01 12:00:41,442: root --> connecting to filter stream for {'track': u'#MakeAmericaGreatAgain, #MAGA, Make America Great Again', 'stall_warning': True}
2017-03-01 12:00:41,443: requests.packages.urllib3.connectionpool --> Resetting dropped connection: stream.twitter.com
2017-03-01 12:00:41,444: requests.packages.urllib3.connectionpool --> Starting new HTTPS connection (3): stream.twitter.com
2017-03-01 12:00:41,630: root --> caught connection error HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 500 [Errno 104] Connection reset by peer',))) on 1 try
2017-03-01 12:00:41,630: root --> closing existing http session
2017-03-01 12:00:41,631: root --> closing last response
2017-03-01 12:00:41,631: root --> creating http session
Traceback (most recent call last):
2017-03-01 12:00:41,632: requests.packages.urllib3.connectionpool --> Starting new HTTPS connection (1): stream.twitter.com
  File "/usr/local/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/site-packages/warcprox/warcprox.py", line 158, in __init__
    warcprox.mitmproxy.MitmProxyHandler.__init__(self, request, client_address, server)
  File "/usr/local/lib/python2.7/site-packages/warcprox/mitmproxy.py", line 25, in __init__
    http_server.BaseHTTPRequestHandler.__init__(self, request, client_address, server)
  File "/usr/local/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/local/lib/python2.7/site-packages/warcprox/warcprox.py", line 241, in finish
    warcprox.mitmproxy.MitmProxyHandler.finish(self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/local/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/local/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
2017-03-01 12:01:49,369: root --> keep-alive
2017-03-01 12:02:16,693: root --> keep-alive
2017-03-01 12:03:18,148: root --> keep-alive
2017-03-01 12:13:28,096: root --> keep-alive
2017-03-01 12:20:54,026: root --> keep-alive
2017-03-01 12:22:10,461: root --> Stopping filter
2017-03-01 12:22:10,462: sfmutils.warcprox --> Shutting down warcprox
Traceback (most recent call last):
  File "/usr/local/bin/warcprox", line 8, in <module>
    warcprox.main.main()
  File "/usr/local/lib/python2.7/site-packages/warcprox/main.py", line 144, in main
    controller.run_until_shutdown()
  File "/usr/local/lib/python2.7/site-packages/warcprox/controller.py", line 74, in run_until_shutdown
    self.proxy.server_close()
  File "/usr/local/lib/python2.7/site-packages/warcprox/warcprox.py", line 326, in server_close
    handler.interrupt()
  File "/usr/local/lib/python2.7/site-packages/warcprox/warcprox.py", line 256, in interrupt
    self._proxy_sock.shutdown(socket.SHUT_RDWR)
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 107] Transport endpoint is not connected
```

**Comment by justinlittman** [comment]
Fixed by:
* https://github.com/gwu-libraries/sfm-utils/pull/32
* https://github.com/gwu-libraries/warcprox/commit/130c6d828d1d2c541b6fc9dce6f580452b1fb05c

A new version of warcprox will need to be made as part of this release.
