### ISSUE TITLE
Twitter harvester unicode error

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#764]
From production:
```
2017-03-27 11:59:15,484 995 INFO Thread-5 warcprox.warcprox.WarcProxyHandler.log_message(mitmproxy.py:147) WarcProxyHandler localhost - - [27/Mar/2017 11:59:15] "GET /1.1/users/lookup.json?screen_name=ScottGottliebMD+%E2%80%8F HTTP/1.1" 404 924
2017-03-27 11:59:15,485: root --> no users matching ScottGottliebMD ‏
2017-03-27 11:59:15,485: sfmutils.warcprox --> Shutting down warcprox
2017-03-27 11:59:15,512 995 INFO WarcWriterThread warcprox.warcwriter.WarcWriterThread.run(warcwriter.py:292) recorded_url.warcprox_meta={} for https://api.twitter.com/1.1/users/lookup.json?screen_name=ScottGottliebMD+%E2%80%8F
2017-03-27 11:59:15,885 995 INFO MainThread warcprox.warcprox.WarcProxy.server_close(warcprox.py:322) WarcProxy shutting down
2017-03-27 11:59:16,013 995 INFO WarcWriterThread warcprox.warcwriter.WarcWriterThread.run(warcwriter.py:317) WarcWriterThread shutting down
2017-03-27 11:59:16,013 995 INFO WarcWriterThread warcprox.warcwriter.WarcWriter.close_writer(warcwriter.py:168) closing 8449a90ed5ae4408822936e97ff02a6d-20170327155915054-00000-995-bd0269a15349-8000.warc.gz
2017-03-27 11:59:16,486: sfmutils.harvester --> Unknown error raised during harvest: 'ascii' codec can't encode character u'\u200f' in position 16: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sfmutils/harvester.py", line 236, in on_message
    self.harvest_seeds()
  File "twitter_harvester.py", line 54, in harvest_seeds
    self.user_timeline()
  File "twitter_harvester.py", line 106, in user_timeline
    msg = "User id not found for user {} because account is not found or suspended".format(screen_name)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u200f' in position 16: ordinal not in range(128)
```

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-twitter-harvester/commit/a781fcc5ad3e92344393952d70190dacab6a4c66
