### ISSUE TITLE
deserialize collection set with query error

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-ui#785]
### Steps
1. serialize the POE collection 
2. deserialize the collection.
### Expect Result
Instance import data without error.
### Actutal Error
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/sfm-ui/sfm/ui/management/commands/deserializecollectionset.py", line 20, in handle
    serializer.deserialize_collection_set(options["collection_set_path"])
  File "/opt/sfm-ui/sfm/ui/serialize.py", line 331, in deserialize_collection_set
    self.deserialize_collection(collection_path)
  File "/opt/sfm-ui/sfm/ui/serialize.py", line 438, in deserialize_collection
    "seed_id", Seed)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/sfm-ui/sfm/ui/serialize.py", line 509, in _deserialize_historical_objects
    for d_obj in self._deserialize_iter(historical_record_filepath):
  File "/opt/sfm-ui/sfm/ui/serialize.py", line 533, in _deserialize_iter
    for d_obj in serializers.deserialize("json", f):
  File "/usr/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 85, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 79, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/usr/local/lib/python2.7/site-packages/django/core/serializers/python.py", line 139, in Deserializer
    obj = field.rel.to._default_manager.db_manager(db).get_by_natural_key(*field_value)
  File "/opt/sfm-ui/sfm/ui/models.py", line 271, in get_by_natural_key
    return self.get(collection_id=collection_id)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
django.core.serializers.base.DeserializationError: Collection matching query does not exist.
``` 

### Reason
The `historical_seeds.json` contains a seed record which can't find on `seeds.json`. It gets a query match error. The additional seed is:
```
{
    "fields": {
        "history_type": "+",
        "uid": "",
        "date_updated": "2016-10-04T15:39:54.597Z",
        "is_active": true,
        "collection": [
            "8b9627b317ca4b6eb333b844d97001d5"
        ],
        "history_note": "",
        "token": "{\"track\": \"#debate, #debates, #debatenight, #debate2016, #debates2016, vice-presidential debate, vice presidential debate, vp debate\", \"follow\": \"22203756, 172858784\"}",
        "is_valid": true,
        "seed_id": "e8de2f8bff114712b6e2033d6e6a214d",
        "date_added": "2016-10-04T15:39:54.594Z",
        "history_user": [
            "exampleuser"
        ],
        "id": 2700,
        "history_date": "2016-10-04T15:39:54.600Z"
    },
    "model": "ui.historicalseed"
}
```
I think it should be a twitter filter seed, while the POE is a twitter user timeline. Not sure why the example seed has been exported to the historical_seeds.

Another issue is that if the deserialize file is too large, the process would be very slow and it could be one record per second.

**Comment by justinlittman** [comment]
We're running django-simple-history 1.8.0. Latest is 1.8.2.

**Comment by justinlittman** [comment]
I can replicate the problem using a django shell. However, I absolutely cannot figure out why it is happening. Will add a check to the serialization process.

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-ui/pull/797
