### ISSUE TITLE
Twitter Stream Harvester doesn't shutdown cleanly

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#793]
Whenever I stop the Twitter Stream Harvester for an upgrade, a number of the stream harvests get stopped as having failed.

**Comment by justinlittman** [comment]
Found this after a problematic startup:
```
2017-04-26 06:20:16,883: sfmutils.harvester --> Try 1 of 3
2017-04-26 06:20:16,889: sfmutils.warcprox --> Executing warcprox -c /tmp/tmpLF7v8x/warcprox-ca.pem --certs-dir /tmp/tmpLF7v8x --dedup-db-file /dev/null -d /sfm-data/containers/867de084defb/tmp/62fe450cbfec45ce826fc0d220d3fe3a -n 62fe450cbfec45ce826fc0d220d3fe3a -p 8000 -z -v -i
Traceback (most recent call last):
  File "/usr/local/bin/warcprox", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/warcprox/bin/warcprox", line 8, in <module>
    warcprox.main.main()
  File "/opt/warcprox/warcprox/main.py", line 121, in main
    interrupt_on_terminate=args.interrupt)
  File "/opt/warcprox/warcprox/warcprox.py", line 304, in __init__
    http_server.HTTPServer.__init__(self, server_address, req_handler_class, bind_and_activate)
  File "/usr/local/lib/python2.7/SocketServer.py", line 423, in __init__
    self.server_close()
  File "/opt/warcprox/warcprox/warcprox.py", line 336, in server_close
    while self.handlers:
AttributeError: WarcProxy instance has no attribute 'handlers'
2017-04-26 06:20:21,933: __main__ --> Harvest type is twitter_filter
2017-04-26 06:20:21,933: root --> connecting to filter stream for {'track': u'gwu', 'stall_warning': True}
2017-04-26 06:20:21,934: root --> creating http session
2017-04-26 06:20:21,938: root --> posting ('https://stream.twitter.com/1.1/statuses/filter.json', {'track': u'gwu', 'stall_warning': True}) {'headers': {'accept-encoding': 'deflate, gzip'}, 'stream': True}
2017-04-26 06:20:21,948: requests.packages.urllib3.connectionpool --> Starting new HTTPS connection (1): stream.twitter.com
2017-04-26 06:20:22,308: root --> caught connection error ("bad handshake: Error([('rsa routines', 'RSA_padding_check_PKCS1_type_1', 'block type is not 01'), ('rsa routines', 'RSA_EAY_PUBLIC_DECRYPT', 'padding check failed'), ('asn1 encoding routines', 'ASN1_item_verify', 'EVP lib'), ('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",) on 1 try
2017-04-26 06:20:22,308: root --> closing existing http session
2017-04-26 06:20:22,308: root --> creating http session
```

Fixed by changing the ordering within WarcProxy.__init__().

**Comment by justinlittman** [comment]
Problem also appears to be that WarcProx slows down too slowly. Found a way to shutdown faster when the client breaks the connection.

Also, added interrupting of sleep to Twarc: https://github.com/DocNow/twarc/pull/162

**Comment by justinlittman** [comment]
Also, suspect that there is a race condition on picking a port:
```
2017-04-26 07:06:29,491: sfmutils.warcprox --> Executing warcprox -c /tmp/tmpdvbUQh/warcprox-ca.pem --certs-dir /tmp/tmpdvbUQh --dedup-db-file /dev/null -d /sfm-data/containers/7523b268a09e/tmp/787ccbfab3a9480f816fff5397a7b5d8 -n 787ccbfab3a9480f816fff5397a7b5d8 -p 8002 -z -v -i
Traceback (most recent call last):
  File "/usr/local/bin/warcprox", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/warcprox/bin/warcprox", line 8, in <module>
    warcprox.main.main()
  File "/opt/warcprox/warcprox/main.py", line 121, in main
    interrupt_on_terminate=args.interrupt)
  File "/opt/warcprox/warcprox/warcprox.py", line 326, in __init__
    http_server.HTTPServer.__init__(self, server_address, req_handler_class, bind_and_activate)
  File "/usr/local/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
```

so made selecting a port random.

**Comment by justinlittman** [comment]
This ticket depends on:
* Latest master for warcprox.
* https://github.com/gwu-libraries/sfm-utils/pull/34
* https://github.com/gwu-libraries/sfm-twitter-harvester/pull/38

Steps to test:
1. Start a bunch of filter streams. (I used 5.) Make them a mixture of high and low velocity filters.
2. Wait
3. Stop the harvester with `docker-compose stop -t 180 twitterstreamharvester`.
4. Verify that all harvests are marked as PAUSED.
5. Start the harvester with `docker-compose up -d`.
6. Wait
7. Verify that all harvests are RUNNING.

**Comment by justinlittman** [comment]
Before closing, this ticket will require a new release of Warcprox and possibly a different (released) version of Twarc.
