### ISSUE TITLE
Null seed causes harvester crash

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#911]
It is possible to create a null seed using bulk import. The causes the harvester to crash.

![screen shot 2018-01-19 at 3 05 03 pm](https://user-images.githubusercontent.com/588335/35169387-6601245e-fd2a-11e7-9626-302d5fa70649.png)

![screen shot 2018-01-19 at 3 04 41 pm](https://user-images.githubusercontent.com/588335/35169395-6b08925c-fd2a-11e7-8acd-5cdd6e9f3af1.png)

```
2018-01-19 11:53:28,707: sfmutils.harvester --> Unknown error raised during harvest: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sfmutils/harvester.py", line 238, in on_message
    self.harvest_seeds()
  File "twitter_harvester.py", line 54, in harvest_seeds
    self.user_timeline()
  File "twitter_harvester.py", line 116, in user_timeline
    assert screen_name or user_id
AssertionError
Traceback (most recent call last):
  File "twitter_harvester.py", line 289, in <module>
    TwitterHarvester.main(TwitterHarvester, QUEUE, [SEARCH_ROUTING_KEY, TIMELINE_ROUTING_KEY])
  File "/usr/local/lib/python2.7/site-packages/sfmutils/harvester.py", line 655, in main
    harvester.run()
  File "/usr/local/lib/python2.7/site-packages/kombu/mixins.py", line 170, in run
    for _ in self.consume(limit=None, **kwargs):
  File "/usr/local/lib/python2.7/site-packages/kombu/mixins.py", line 192, in consume
    conn.drain_events(timeout=safety_interval)
  File "/usr/local/lib/python2.7/site-packages/librabbitmq/__init__.py", line 220, in drain_events
    self._basic_recv(timeout)
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 623, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 589, in receive
    [callback(body, message) for callback in callbacks]
  File "/usr/local/lib/python2.7/site-packages/sfmutils/consumer.py", line 104, in _callback
    self.on_message()
  File "/usr/local/lib/python2.7/site-packages/sfmutils/harvester.py", line 250, in on_message
    self.result.errors.append(Msg(CODE_UNKNOWN_ERROR, str(e)))
  File "/usr/local/lib/python2.7/site-packages/sfmutils/result.py", line 75, in __init__
    assert message
AssertionError
```

**Comment by justinlittman** [comment]
Looks like the cause is when the screen name is "null":
```
wikileaks
null
The_UnSilent_
```
