### ISSUE TITLE
ELK / Elasticsearch not starting

### ISSUE THREAD

**Issue by nloui** [gwu-libraries/sfm-ui#916]
Getting this in the docker Elasticsearch logs... curious if anyone else has stumbled into it?

`Waiting for elasticsearch and kibana
Check 1
[2018-03-08T03:26:28,109][INFO ][o.e.n.Node               ] [sfm_es_node_1] initializing ...
[2018-03-08T03:26:29,791][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [sfm_es_node_1] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/sfm-data/elk/sfm_es_1/data/sfm_prod_1]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.0.jar:5.3.0]
Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/sfm-data/elk/sfm_es_1/data/sfm_prod_1]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:260) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.node.Node.<init>(Node.java:258) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.node.Node.<init>(Node.java:238) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.0.jar:5.3.0]
	... 6 more
Caused by: java.io.IOException: failed to obtain lock on /sfm-data/elk/sfm_es_1/data/nodes/0
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:239) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.node.Node.<init>(Node.java:258) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.node.Node.<init>(Node.java:238) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.0.jar:5.3.0]
	... 6 more
Caused by: java.io.IOException: Mount point not found
	at sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:91) ~[?:?]
	at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:65) ~[?:?]
	at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44) ~[?:?]
	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51) ~[?:?]
	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:368) ~[?:?]
	at java.nio.file.Files.getFileStore(Files.java:1461) ~[?:1.8.0_92-internal]
	at org.elasticsearch.env.ESFileStore.getMatchingFileStore(ESFileStore.java:107) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.env.Environment.getFileStore(Environment.java:340) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.env.NodeEnvironment$NodePath.<init>(NodeEnvironment.java:108) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:227) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.node.Node.<init>(Node.java:258) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.node.Node.<init>(Node.java:238) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.0.jar:5.3.0]
	... 6 more
`

**Comment by nloui** [comment]
Upgrading to the master version of the Docker containers seems to have resolved

**Comment by justinlittman** [comment]
Thanks @nloui. If anything comes up, let us know.

**Comment by nloui** [comment]
Cool, now Logstash is throwing this error:

elasticsearch:9200 is available.
Check 18
elasticsearch status is red, wait 30 seconds to try again.
elasticsearch status is red, wait 30 seconds to try again.
elasticsearch status is red, wait 30 seconds to try again.
elasticsearch status is red, wait 30 seconds to try again.
elasticsearch status is red, wait 30 seconds to try again.
elasticsearch status is red, wait 30 seconds to try again.
elasticsearch status is red, wait 30 seconds to try again.
elasticsearch status is red, wait 30 seconds to try again.

Elasticsearch is running.

**Comment by justinlittman** [comment]
@nloui A few thoughts to share with you on sfm-elk:
* The current configuration won't scale very well to large numbers of tweets. Two problems in particular: ES is better off as a cluster and the current approach to loading tweets creates huge numbers of shards, which slows down ES, especially starting up.
* I'm thinking of deprecating sfm-elk in the near future in favor of https://github.com/justinlittman/TweetSets. In TweetSets, both loading and scaling are better thought out and handled. Though TweetSets provides a Flask UI, Kibana can also be pointed at the ElasticSearch index. (I'm working on this now. Follow the TweetSets repo for updates.)
* The more memory, the better.
* Contrary to the notes in the docker-compose, the Java memory limit should be set to half of the container memory limit. This should help with stability.

As noted in the docs, sfm-elk is an experiment. The basic idea proved useful, but we've learned a lot about the correct implementation.

**Comment by nloui** [comment]
Yeah, I was able to tweak the settings to get it sort of working, but I'm definitely pushing the limits of it.  Look forward to seeing if TweetSets is implemented.  Thanks for the info and the project!
