### ISSUE TITLE
Cannot connect to proxy error

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#944]
Steps to reproduce:
1. Perform a harvest on a Twitter user timeline collection with a large number of seeds, say 10K.
2. Wait

Expected result:
Harvest completes successfully.

Actual result:
```
Error messages:
- HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?count=200&user_id=14935240&since_id=1021413145175240704&tweet_mode=extended (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
```

This appears to be because warcprox becomes unavailable. I believe it is a problem with the thread limiting implemented in warcprox 2.

**Comment by kanihal** [comment]
has this been fixed?
I am getting these messages for almost every harvest. I am behind a corporate proxy running only one instance of `harvester` running.

>Log from tweet_harvester container
```

2019-04-24 16:44:36,332: sfmutils.harvester --> Unknown error raised during harvest: HTTPSConnectionPool(host='api.twitter.com', port=443): Read timed out. (read timeout=31)


Traceback (most recent call last):


  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request


    six.raise_from(e, None)


  File "<string>", line 2, in raise_from


  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request


    httplib_response = conn.getresponse()


  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse


    response.begin()


  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin


    version, status, reason = self._read_status()


  File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status


    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")


  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto


    return self._sock.recv_into(b)


  File "/usr/local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 307, in recv_into


    raise timeout('The read operation timed out')


socket.timeout: The read operation timed out




During handling of the above exception, another exception occurred:




Traceback (most recent call last):


  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send


    timeout=timeout


  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen


    _stacktrace=sys.exc_info()[2])


  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment


    raise six.reraise(type(error), error, _stacktrace)


  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise


    raise value


  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen


    chunked=chunked)


  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request


    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)


  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout


    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)


urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.twitter.com', port=443): Read timed out. (read timeout=31)




During handling of the above exception, another exception occurred:




Traceback (most recent call last):


  File "/usr/local/lib/python3.6/site-packages/sfmutils/harvester.py", line 239, in on_message


    self.harvest_seeds()


  File "twitter_harvester.py", line 35, in harvest_seeds


    self._create_twarc()


  File "twitter_harvester.py", line 58, in _create_twarc


    tweet_mode="extended")


  File "/usr/local/lib/python3.6/site-packages/twarc/client.py", line 69, in __init__


    self.validate_keys()


  File "/usr/local/lib/python3.6/site-packages/twarc/client.py", line 755, in validate_keys


    self.get(url)


  File "/usr/local/lib/python3.6/site-packages/twarc/decorators.py", line 14, in new_f


    resp = f(*args, **kwargs)


  File "/usr/local/lib/python3.6/site-packages/twarc/decorators.py", line 68, in new_f


    return f(self, *args, **kwargs)


  File "/usr/local/lib/python3.6/site-packages/twarc/decorators.py", line 88, in new_f


    return f(self, *args, **kwargs)


  File "/usr/local/lib/python3.6/site-packages/twarc/decorators.py", line 99, in new_f


    return f(self, *args, **kwargs)


  File "/usr/local/lib/python3.6/site-packages/twarc/client.py", line 643, in get


    **kwargs)


  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 546, in get


    return self.request('GET', url, **kwargs)


  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request


    resp = self.send(prep, **send_kwargs)


  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send


    r = adapter.send(request, **kwargs)


  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 529, in send


    raise ReadTimeout(e, request=request)


requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Read timed out. (read timeout=31)
```

**Comment by lwrubel** [comment]
Hi @kanihal, 
When this kind of error occurs, we recommend in our [troubleshooting documentation](https://sfm.readthedocs.io/en/latest/troubleshooting.html#connection-errors-when-harvesting) that you stop and start the container: 

docker-compose stop twitterrestharvester
docker-compose up -d

Have you tried that yet, and did you still get the same error?
