### ISSUE TITLE
Serializecollectionset management command error

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#945]
Steps to reproduce:
1. `docker exec -it sfm_ui_1 /bin/bash`
2. `cd sfm`
3. `./manage.py serializecollectionset d62ec849d12`

Expected result:
Management command executes.

Actual result:
```
23445fa6cd533f99ff8f42/sfm-ui/sfm# ./manage.py serializecollectionset d62ec849d12
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 216, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/sfm-ui/sfm/ui/management/commands/serializecollectionset.py", line 3, in <module>
    from sfm.ui.models import CollectionSet
ModuleNotFoundError: No module named 'sfm.ui'
```

**Comment by justinlittman** [comment]
Same applies to other serialize and deserialize management commands.
