### ISSUE TITLE
Weibo export fails with unexpected json

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#983]
When exporting from at least some of the Weibo search collections in collection set 2, such as collection 172 (Topic_贿赂), no export is provided and export status stays as "Running". 

Docker sfm_weiboexporter_1 container log shows:

2019-05-06 15:33:13,135: sfmutils.warc_iter --> Iterating over /sfm-data/collection_set/40c02df38fc44b12bd3f8dedb1948999/456f3587b02f480ab127883f42d0120f/2017/09/19/16/287c996639f64bcfaec0137158d531f4-20170919160140561-00000-6509-bd35ec264508-8264.warc.gz
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 623, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 589, in receive
    [callback(body, message) for callback in callbacks]
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 589, in <listcomp>
    [callback(body, message) for callback in callbacks]
  File "/usr/local/lib/python3.6/site-packages/sfmutils/consumer.py", line 111, in _callback
    self.on_message()
  File "/usr/local/lib/python3.6/site-packages/sfmutils/exporter.py", line 125, in on_message
    export_formats[export_format][1](table, filepath)
  File "/usr/local/lib/python3.6/site-packages/petl/io/csv.py", line 109, in tocsv
    write_header=write_header, **csvargs)
  File "/usr/local/lib/python3.6/site-packages/petl/io/csv_py3.py", line 44, in tocsv_impl
    _writecsv(table, source=source, mode='wb', **kwargs)
  File "/usr/local/lib/python3.6/site-packages/petl/io/csv_py3.py", line 59, in _writecsv
    for row in rows:
  File "/usr/local/lib/python3.6/site-packages/sfmutils/exporter.py", line 354, in chunk
    for more in islice(iterator_warc, split_size):
  File "/usr/local/lib/python3.6/site-packages/sfmutils/warc_iter.py", line 74, in iter
    for item_type, item_id, item_date, item in self._item_iter(record_url, json_obj):
  File "/opt/sfm-weibo-harvester/weibo_warc_iter.py", line 17, in _item_iter
    for status in json_obj["statuses"]:
KeyError: 'statuses'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "weibo_exporter.py", line 87, in <module>
    WeiboExporter.main(WeiboExporter, QUEUE, [SEARCH_ROUTING_KEY, TIME_LINE_ROUTING_KEY])
  File "/usr/local/lib/python3.6/site-packages/sfmutils/exporter.py", line 286, in main
    exporter.run()
  File "/usr/local/lib/python3.6/site-packages/kombu/mixins.py", line 170, in run
    for _ in self.consume(limit=None, **kwargs):
  File "/usr/local/lib/python3.6/site-packages/kombu/mixins.py", line 192, in consume
    conn.drain_events(timeout=safety_interval)
  File "/usr/local/lib/python3.6/site-packages/librabbitmq/__init__.py", line 227, in drain_events
    self._basic_recv(timeout)
SystemError: <built-in method _basic_recv of Connection object at 0x7f6efa1bb9d8> returned a result with an error set

**Comment by lwrubel** [comment]
The API response that the exporter is not handling is:

{'error': 'source paramter(appkey) is missing', 'error_code': 10006, 'request': '/2/search/topics.json'}

**Comment by lwrubel** [comment]
Weibo documentation about error code responses: https://open.weibo.com/wiki/Error_code

**Comment by lwrubel** [comment]
Has PR: https://github.com/gwu-libraries/sfm-weibo-harvester/pull/33
