### ISSUE TITLE
Weibo test of export is failing

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#988]
The following test is failing: tests.test_weibo_exporter.TestWeiboExporterVcr. 

```
======================================================================
ERROR: test_export_collection (tests.test_weibo_exporter.TestWeiboExporterVcr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lwrubel/projects/sfm-weibo-harvester/ENV/lib/python3.6/site-packages/vcr/cassette.py", line 109, in __call__
    function, args, kwargs
  File "/home/lwrubel/projects/sfm-weibo-harvester/ENV/lib/python3.6/site-packages/vcr/cassette.py", line 124, in _execute_function
    return self._handle_function(fn=handle_function)
  File "/home/lwrubel/projects/sfm-weibo-harvester/ENV/lib/python3.6/site-packages/vcr/cassette.py", line 148, in _handle_function
    return fn(cassette)
  File "/home/lwrubel/projects/sfm-weibo-harvester/ENV/lib/python3.6/site-packages/vcr/cassette.py", line 117, in handle_function
    return function(*args, **kwargs)
  File "/home/lwrubel/projects/sfm-weibo-harvester/tests/test_weibo_exporter.py", line 69, in test_export_collection
    self.exporter.on_message()
  File "/home/lwrubel/projects/sfm-utils/sfmutils/exporter.py", line 125, in on_message
    export_formats[export_format][1](table, filepath)
  File "/home/lwrubel/projects/sfm-weibo-harvester/ENV/lib/python3.6/site-packages/petl/io/csv.py", line 109, in tocsv
    write_header=write_header, **csvargs)
  File "/home/lwrubel/projects/sfm-weibo-harvester/ENV/lib/python3.6/site-packages/petl/io/csv_py3.py", line 44, in tocsv_impl
    _writecsv(table, source=source, mode='wb', **kwargs)
  File "/home/lwrubel/projects/sfm-weibo-harvester/ENV/lib/python3.6/site-packages/petl/io/csv_py3.py", line 60, in _writecsv
    writer.writerow(row)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 43-47: ordinal not in range(128)

----------------------------------------------------------------------
Ran 18 tests in 0.119s
```

**Comment by lwrubel** [comment]
This test passes inside the container and in Travis CI, so it's likely an issue with configuration in my dev instance. I've created a test_config.py as described in the README.md.
